FROM alpine:3.18

ENV UID=1337 \
    GID=1337

RUN apk add --no-cache ffmpeg su-exec ca-certificates bash jq curl yq

ARG EXECUTABLE=./mautrix-gmessages
COPY $EXECUTABLE /usr/bin/mautrix-gmessages
COPY ./example-config.yaml /opt/mautrix-gmessages/example-config.yaml
COPY ./docker-run.sh /docker-run.sh
VOLUME /data

CMD ["/docker-run.sh"]
