-- v0 -> v3 (compatible with v3+): Latest schema
CREATE TABLE gmessages_login_prefix(
    -- only: postgres
    prefix BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    -- only: sqlite (line commented)
--	prefix INTEGER PRIMARY KEY,
    login_id TEXT NOT NULL,

    CONSTRAINT gmessages_login_prefix_login_id_key UNIQUE (login_id)
);
