// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: authentication.proto

package gmproto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "go.mau.fi/util/pblite"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BrowserType int32

const (
	BrowserType_UNKNOWN_BROWSER_TYPE BrowserType = 0
	BrowserType_OTHER                BrowserType = 1
	BrowserType_CHROME               BrowserType = 2
	BrowserType_FIREFOX              BrowserType = 3
	BrowserType_SAFARI               BrowserType = 4
	BrowserType_OPERA                BrowserType = 5
	BrowserType_IE                   BrowserType = 6
	BrowserType_EDGE                 BrowserType = 7
)

// Enum value maps for BrowserType.
var (
	BrowserType_name = map[int32]string{
		0: "UNKNOWN_BROWSER_TYPE",
		1: "OTHER",
		2: "CHROME",
		3: "FIREFOX",
		4: "SAFARI",
		5: "OPERA",
		6: "IE",
		7: "EDGE",
	}
	BrowserType_value = map[string]int32{
		"UNKNOWN_BROWSER_TYPE": 0,
		"OTHER":                1,
		"CHROME":               2,
		"FIREFOX":              3,
		"SAFARI":               4,
		"OPERA":                5,
		"IE":                   6,
		"EDGE":                 7,
	}
)

func (x BrowserType) Enum() *BrowserType {
	p := new(BrowserType)
	*p = x
	return p
}

func (x BrowserType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BrowserType) Descriptor() protoreflect.EnumDescriptor {
	return file_authentication_proto_enumTypes[0].Descriptor()
}

func (BrowserType) Type() protoreflect.EnumType {
	return &file_authentication_proto_enumTypes[0]
}

func (x BrowserType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BrowserType.Descriptor instead.
func (BrowserType) EnumDescriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{0}
}

type DeviceType int32

const (
	DeviceType_UNKNOWN_DEVICE_TYPE DeviceType = 0
	DeviceType_WEB                 DeviceType = 1
	DeviceType_TABLET              DeviceType = 2
	DeviceType_PWA                 DeviceType = 3
)

// Enum value maps for DeviceType.
var (
	DeviceType_name = map[int32]string{
		0: "UNKNOWN_DEVICE_TYPE",
		1: "WEB",
		2: "TABLET",
		3: "PWA",
	}
	DeviceType_value = map[string]int32{
		"UNKNOWN_DEVICE_TYPE": 0,
		"WEB":                 1,
		"TABLET":              2,
		"PWA":                 3,
	}
)

func (x DeviceType) Enum() *DeviceType {
	p := new(DeviceType)
	*p = x
	return p
}

func (x DeviceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceType) Descriptor() protoreflect.EnumDescriptor {
	return file_authentication_proto_enumTypes[1].Descriptor()
}

func (DeviceType) Type() protoreflect.EnumType {
	return &file_authentication_proto_enumTypes[1]
}

func (x DeviceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceType.Descriptor instead.
func (DeviceType) EnumDescriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{1}
}

type BrowserDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserAgent     string                 `protobuf:"bytes,1,opt,name=userAgent,proto3" json:"userAgent,omitempty"`
	BrowserType   BrowserType            `protobuf:"varint,2,opt,name=browserType,proto3,enum=authentication.BrowserType" json:"browserType,omitempty"`
	OS            string                 `protobuf:"bytes,3,opt,name=OS,proto3" json:"OS,omitempty"`
	DeviceType    DeviceType             `protobuf:"varint,6,opt,name=deviceType,proto3,enum=authentication.DeviceType" json:"deviceType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrowserDetails) Reset() {
	*x = BrowserDetails{}
	mi := &file_authentication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrowserDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowserDetails) ProtoMessage() {}

func (x *BrowserDetails) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowserDetails.ProtoReflect.Descriptor instead.
func (*BrowserDetails) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{0}
}

func (x *BrowserDetails) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *BrowserDetails) GetBrowserType() BrowserType {
	if x != nil {
		return x.BrowserType
	}
	return BrowserType_UNKNOWN_BROWSER_TYPE
}

func (x *BrowserDetails) GetOS() string {
	if x != nil {
		return x.OS
	}
	return ""
}

func (x *BrowserDetails) GetDeviceType() DeviceType {
	if x != nil {
		return x.DeviceType
	}
	return DeviceType_UNKNOWN_DEVICE_TYPE
}

type Device struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	SourceID      string                 `protobuf:"bytes,2,opt,name=sourceID,proto3" json:"sourceID,omitempty"`
	Network       string                 `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_authentication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{1}
}

func (x *Device) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *Device) GetSourceID() string {
	if x != nil {
		return x.SourceID
	}
	return ""
}

func (x *Device) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

type ConfigVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,3,opt,name=Year,proto3" json:"Year,omitempty"`
	Month         int32                  `protobuf:"varint,4,opt,name=Month,proto3" json:"Month,omitempty"`
	Day           int32                  `protobuf:"varint,5,opt,name=Day,proto3" json:"Day,omitempty"`
	V1            int32                  `protobuf:"varint,7,opt,name=V1,proto3" json:"V1,omitempty"`
	V2            int32                  `protobuf:"varint,9,opt,name=V2,proto3" json:"V2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigVersion) Reset() {
	*x = ConfigVersion{}
	mi := &file_authentication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigVersion) ProtoMessage() {}

func (x *ConfigVersion) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigVersion.ProtoReflect.Descriptor instead.
func (*ConfigVersion) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigVersion) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *ConfigVersion) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *ConfigVersion) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *ConfigVersion) GetV1() int32 {
	if x != nil {
		return x.V1
	}
	return 0
}

func (x *ConfigVersion) GetV2() int32 {
	if x != nil {
		return x.V2
	}
	return 0
}

type SignInGaiaRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	AuthMessage   *AuthMessage             `protobuf:"bytes,1,opt,name=authMessage,proto3" json:"authMessage,omitempty"`
	Inner         *SignInGaiaRequest_Inner `protobuf:"bytes,2,opt,name=inner,proto3" json:"inner,omitempty"`
	UnknownInt3   int32                    `protobuf:"varint,3,opt,name=unknownInt3,proto3" json:"unknownInt3,omitempty"`
	Network       string                   `protobuf:"bytes,4,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInGaiaRequest) Reset() {
	*x = SignInGaiaRequest{}
	mi := &file_authentication_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInGaiaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInGaiaRequest) ProtoMessage() {}

func (x *SignInGaiaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInGaiaRequest.ProtoReflect.Descriptor instead.
func (*SignInGaiaRequest) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{3}
}

func (x *SignInGaiaRequest) GetAuthMessage() *AuthMessage {
	if x != nil {
		return x.AuthMessage
	}
	return nil
}

func (x *SignInGaiaRequest) GetInner() *SignInGaiaRequest_Inner {
	if x != nil {
		return x.Inner
	}
	return nil
}

func (x *SignInGaiaRequest) GetUnknownInt3() int32 {
	if x != nil {
		return x.UnknownInt3
	}
	return 0
}

func (x *SignInGaiaRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

type SignInGaiaResponse struct {
	state            protoimpl.MessageState         `protogen:"open.v1"`
	Header           *SignInGaiaResponse_Header     `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	MaybeBrowserUUID string                         `protobuf:"bytes,2,opt,name=maybeBrowserUUID,proto3" json:"maybeBrowserUUID,omitempty"`
	DeviceData       *SignInGaiaResponse_DeviceData `protobuf:"bytes,3,opt,name=deviceData,proto3" json:"deviceData,omitempty"`
	TokenData        *TokenData                     `protobuf:"bytes,4,opt,name=tokenData,proto3" json:"tokenData,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SignInGaiaResponse) Reset() {
	*x = SignInGaiaResponse{}
	mi := &file_authentication_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInGaiaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInGaiaResponse) ProtoMessage() {}

func (x *SignInGaiaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInGaiaResponse.ProtoReflect.Descriptor instead.
func (*SignInGaiaResponse) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{4}
}

func (x *SignInGaiaResponse) GetHeader() *SignInGaiaResponse_Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *SignInGaiaResponse) GetMaybeBrowserUUID() string {
	if x != nil {
		return x.MaybeBrowserUUID
	}
	return ""
}

func (x *SignInGaiaResponse) GetDeviceData() *SignInGaiaResponse_DeviceData {
	if x != nil {
		return x.DeviceData
	}
	return nil
}

func (x *SignInGaiaResponse) GetTokenData() *TokenData {
	if x != nil {
		return x.TokenData
	}
	return nil
}

type GaiaPairingRequestContainer struct {
	state                           protoimpl.MessageState `protogen:"open.v1"`
	PairingAttemptID                string                 `protobuf:"bytes,1,opt,name=pairingAttemptID,proto3" json:"pairingAttemptID,omitempty"`
	BrowserDetails                  *BrowserDetails        `protobuf:"bytes,2,opt,name=browserDetails,proto3" json:"browserDetails,omitempty"`
	StartTimestamp                  int64                  `protobuf:"varint,3,opt,name=startTimestamp,proto3" json:"startTimestamp,omitempty"`
	Data                            []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	ProposedVerificationCodeVersion int32                  `protobuf:"varint,5,opt,name=proposedVerificationCodeVersion,proto3" json:"proposedVerificationCodeVersion,omitempty"`
	ProposedKeyDerivationVersion    int32                  `protobuf:"varint,6,opt,name=proposedKeyDerivationVersion,proto3" json:"proposedKeyDerivationVersion,omitempty"`
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *GaiaPairingRequestContainer) Reset() {
	*x = GaiaPairingRequestContainer{}
	mi := &file_authentication_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GaiaPairingRequestContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GaiaPairingRequestContainer) ProtoMessage() {}

func (x *GaiaPairingRequestContainer) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GaiaPairingRequestContainer.ProtoReflect.Descriptor instead.
func (*GaiaPairingRequestContainer) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{5}
}

func (x *GaiaPairingRequestContainer) GetPairingAttemptID() string {
	if x != nil {
		return x.PairingAttemptID
	}
	return ""
}

func (x *GaiaPairingRequestContainer) GetBrowserDetails() *BrowserDetails {
	if x != nil {
		return x.BrowserDetails
	}
	return nil
}

func (x *GaiaPairingRequestContainer) GetStartTimestamp() int64 {
	if x != nil {
		return x.StartTimestamp
	}
	return 0
}

func (x *GaiaPairingRequestContainer) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GaiaPairingRequestContainer) GetProposedVerificationCodeVersion() int32 {
	if x != nil {
		return x.ProposedVerificationCodeVersion
	}
	return 0
}

func (x *GaiaPairingRequestContainer) GetProposedKeyDerivationVersion() int32 {
	if x != nil {
		return x.ProposedKeyDerivationVersion
	}
	return 0
}

type GaiaPairingResponseContainer struct {
	state                            protoimpl.MessageState `protogen:"open.v1"`
	FinishErrorType                  int32                  `protobuf:"varint,1,opt,name=finishErrorType,proto3" json:"finishErrorType,omitempty"`
	FinishErrorCode                  int32                  `protobuf:"varint,2,opt,name=finishErrorCode,proto3" json:"finishErrorCode,omitempty"`
	UnknownInt3                      int32                  `protobuf:"varint,3,opt,name=unknownInt3,proto3" json:"unknownInt3,omitempty"` // For init, 1
	SessionUUID                      string                 `protobuf:"bytes,4,opt,name=sessionUUID,proto3" json:"sessionUUID,omitempty"`
	Data                             []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	ConfirmedVerificationCodeVersion int32                  `protobuf:"varint,6,opt,name=confirmedVerificationCodeVersion,proto3" json:"confirmedVerificationCodeVersion,omitempty"`
	ConfirmedKeyDerivationVersion    int32                  `protobuf:"varint,7,opt,name=confirmedKeyDerivationVersion,proto3" json:"confirmedKeyDerivationVersion,omitempty"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *GaiaPairingResponseContainer) Reset() {
	*x = GaiaPairingResponseContainer{}
	mi := &file_authentication_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GaiaPairingResponseContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GaiaPairingResponseContainer) ProtoMessage() {}

func (x *GaiaPairingResponseContainer) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GaiaPairingResponseContainer.ProtoReflect.Descriptor instead.
func (*GaiaPairingResponseContainer) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{6}
}

func (x *GaiaPairingResponseContainer) GetFinishErrorType() int32 {
	if x != nil {
		return x.FinishErrorType
	}
	return 0
}

func (x *GaiaPairingResponseContainer) GetFinishErrorCode() int32 {
	if x != nil {
		return x.FinishErrorCode
	}
	return 0
}

func (x *GaiaPairingResponseContainer) GetUnknownInt3() int32 {
	if x != nil {
		return x.UnknownInt3
	}
	return 0
}

func (x *GaiaPairingResponseContainer) GetSessionUUID() string {
	if x != nil {
		return x.SessionUUID
	}
	return ""
}

func (x *GaiaPairingResponseContainer) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GaiaPairingResponseContainer) GetConfirmedVerificationCodeVersion() int32 {
	if x != nil {
		return x.ConfirmedVerificationCodeVersion
	}
	return 0
}

func (x *GaiaPairingResponseContainer) GetConfirmedKeyDerivationVersion() int32 {
	if x != nil {
		return x.ConfirmedKeyDerivationVersion
	}
	return 0
}

type RevokeGaiaPairingRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PairingAttemptID string                 `protobuf:"bytes,1,opt,name=pairingAttemptID,proto3" json:"pairingAttemptID,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RevokeGaiaPairingRequest) Reset() {
	*x = RevokeGaiaPairingRequest{}
	mi := &file_authentication_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeGaiaPairingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeGaiaPairingRequest) ProtoMessage() {}

func (x *RevokeGaiaPairingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeGaiaPairingRequest.ProtoReflect.Descriptor instead.
func (*RevokeGaiaPairingRequest) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{7}
}

func (x *RevokeGaiaPairingRequest) GetPairingAttemptID() string {
	if x != nil {
		return x.PairingAttemptID
	}
	return ""
}

type RPCGaiaData struct {
	state           protoimpl.MessageState        `protogen:"open.v1"`
	Command         int32                         `protobuf:"varint,1,opt,name=command,proto3" json:"command,omitempty"` // 9
	MaybeServerData *RPCGaiaData_UnknownContainer `protobuf:"bytes,108,opt,name=maybeServerData,proto3" json:"maybeServerData,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RPCGaiaData) Reset() {
	*x = RPCGaiaData{}
	mi := &file_authentication_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPCGaiaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCGaiaData) ProtoMessage() {}

func (x *RPCGaiaData) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCGaiaData.ProtoReflect.Descriptor instead.
func (*RPCGaiaData) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{8}
}

func (x *RPCGaiaData) GetCommand() int32 {
	if x != nil {
		return x.Command
	}
	return 0
}

func (x *RPCGaiaData) GetMaybeServerData() *RPCGaiaData_UnknownContainer {
	if x != nil {
		return x.MaybeServerData
	}
	return nil
}

type AuthenticationContainer struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AuthMessage    *AuthMessage           `protobuf:"bytes,1,opt,name=authMessage,proto3" json:"authMessage,omitempty"`
	BrowserDetails *BrowserDetails        `protobuf:"bytes,3,opt,name=browserDetails,proto3" json:"browserDetails,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*AuthenticationContainer_KeyData
	//	*AuthenticationContainer_DeviceData
	Data          isAuthenticationContainer_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticationContainer) Reset() {
	*x = AuthenticationContainer{}
	mi := &file_authentication_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticationContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationContainer) ProtoMessage() {}

func (x *AuthenticationContainer) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationContainer.ProtoReflect.Descriptor instead.
func (*AuthenticationContainer) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{9}
}

func (x *AuthenticationContainer) GetAuthMessage() *AuthMessage {
	if x != nil {
		return x.AuthMessage
	}
	return nil
}

func (x *AuthenticationContainer) GetBrowserDetails() *BrowserDetails {
	if x != nil {
		return x.BrowserDetails
	}
	return nil
}

func (x *AuthenticationContainer) GetData() isAuthenticationContainer_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AuthenticationContainer) GetKeyData() *KeyData {
	if x != nil {
		if x, ok := x.Data.(*AuthenticationContainer_KeyData); ok {
			return x.KeyData
		}
	}
	return nil
}

func (x *AuthenticationContainer) GetDeviceData() *CurrentDeviceData {
	if x != nil {
		if x, ok := x.Data.(*AuthenticationContainer_DeviceData); ok {
			return x.DeviceData
		}
	}
	return nil
}

type isAuthenticationContainer_Data interface {
	isAuthenticationContainer_Data()
}

type AuthenticationContainer_KeyData struct {
	KeyData *KeyData `protobuf:"bytes,4,opt,name=keyData,proto3,oneof"`
}

type AuthenticationContainer_DeviceData struct {
	DeviceData *CurrentDeviceData `protobuf:"bytes,5,opt,name=deviceData,proto3,oneof"`
}

func (*AuthenticationContainer_KeyData) isAuthenticationContainer_Data() {}

func (*AuthenticationContainer_DeviceData) isAuthenticationContainer_Data() {}

type AuthMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestID        string                 `protobuf:"bytes,1,opt,name=requestID,proto3" json:"requestID,omitempty"`
	Network          string                 `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	TachyonAuthToken []byte                 `protobuf:"bytes,6,opt,name=tachyonAuthToken,proto3" json:"tachyonAuthToken,omitempty"`
	ConfigVersion    *ConfigVersion         `protobuf:"bytes,7,opt,name=configVersion,proto3" json:"configVersion,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AuthMessage) Reset() {
	*x = AuthMessage{}
	mi := &file_authentication_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthMessage) ProtoMessage() {}

func (x *AuthMessage) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthMessage.ProtoReflect.Descriptor instead.
func (*AuthMessage) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{10}
}

func (x *AuthMessage) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *AuthMessage) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *AuthMessage) GetTachyonAuthToken() []byte {
	if x != nil {
		return x.TachyonAuthToken
	}
	return nil
}

func (x *AuthMessage) GetConfigVersion() *ConfigVersion {
	if x != nil {
		return x.ConfigVersion
	}
	return nil
}

type RevokeRelayPairingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthMessage   *AuthMessage           `protobuf:"bytes,1,opt,name=authMessage,proto3" json:"authMessage,omitempty"`
	Browser       *Device                `protobuf:"bytes,2,opt,name=browser,proto3" json:"browser,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRelayPairingRequest) Reset() {
	*x = RevokeRelayPairingRequest{}
	mi := &file_authentication_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRelayPairingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRelayPairingRequest) ProtoMessage() {}

func (x *RevokeRelayPairingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRelayPairingRequest.ProtoReflect.Descriptor instead.
func (*RevokeRelayPairingRequest) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{11}
}

func (x *RevokeRelayPairingRequest) GetAuthMessage() *AuthMessage {
	if x != nil {
		return x.AuthMessage
	}
	return nil
}

func (x *RevokeRelayPairingRequest) GetBrowser() *Device {
	if x != nil {
		return x.Browser
	}
	return nil
}

type RevokeRelayPairingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRelayPairingResponse) Reset() {
	*x = RevokeRelayPairingResponse{}
	mi := &file_authentication_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRelayPairingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRelayPairingResponse) ProtoMessage() {}

func (x *RevokeRelayPairingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRelayPairingResponse.ProtoReflect.Descriptor instead.
func (*RevokeRelayPairingResponse) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{12}
}

type RegisterRefreshRequest struct {
	state             protoimpl.MessageState                 `protogen:"open.v1"`
	MessageAuth       *AuthMessage                           `protobuf:"bytes,1,opt,name=messageAuth,proto3" json:"messageAuth,omitempty"`
	CurrBrowserDevice *Device                                `protobuf:"bytes,2,opt,name=currBrowserDevice,proto3" json:"currBrowserDevice,omitempty"`
	UnixTimestamp     int64                                  `protobuf:"varint,3,opt,name=unixTimestamp,proto3" json:"unixTimestamp,omitempty"`
	Signature         []byte                                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	EmptyRefreshArr   *RegisterRefreshRequest_NestedEmptyArr `protobuf:"bytes,13,opt,name=emptyRefreshArr,proto3" json:"emptyRefreshArr,omitempty"`
	MessageType       int32                                  `protobuf:"varint,16,opt,name=messageType,proto3" json:"messageType,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterRefreshRequest) Reset() {
	*x = RegisterRefreshRequest{}
	mi := &file_authentication_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRefreshRequest) ProtoMessage() {}

func (x *RegisterRefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRefreshRequest.ProtoReflect.Descriptor instead.
func (*RegisterRefreshRequest) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{13}
}

func (x *RegisterRefreshRequest) GetMessageAuth() *AuthMessage {
	if x != nil {
		return x.MessageAuth
	}
	return nil
}

func (x *RegisterRefreshRequest) GetCurrBrowserDevice() *Device {
	if x != nil {
		return x.CurrBrowserDevice
	}
	return nil
}

func (x *RegisterRefreshRequest) GetUnixTimestamp() int64 {
	if x != nil {
		return x.UnixTimestamp
	}
	return 0
}

func (x *RegisterRefreshRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *RegisterRefreshRequest) GetEmptyRefreshArr() *RegisterRefreshRequest_NestedEmptyArr {
	if x != nil {
		return x.EmptyRefreshArr
	}
	return nil
}

func (x *RegisterRefreshRequest) GetMessageType() int32 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

type RegisterRefreshResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenData     *TokenData             `protobuf:"bytes,2,opt,name=tokenData,proto3" json:"tokenData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRefreshResponse) Reset() {
	*x = RegisterRefreshResponse{}
	mi := &file_authentication_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRefreshResponse) ProtoMessage() {}

func (x *RegisterRefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRefreshResponse.ProtoReflect.Descriptor instead.
func (*RegisterRefreshResponse) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{14}
}

func (x *RegisterRefreshResponse) GetTokenData() *TokenData {
	if x != nil {
		return x.TokenData
	}
	return nil
}

type RegisterPhoneRelayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coordinates   *CoordinateMessage     `protobuf:"bytes,1,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	Browser       *Device                `protobuf:"bytes,2,opt,name=browser,proto3" json:"browser,omitempty"`
	PairingKey    []byte                 `protobuf:"bytes,3,opt,name=pairingKey,proto3" json:"pairingKey,omitempty"`
	ValidFor      int64                  `protobuf:"varint,4,opt,name=validFor,proto3" json:"validFor,omitempty"`
	AuthKeyData   *TokenData             `protobuf:"bytes,5,opt,name=authKeyData,proto3" json:"authKeyData,omitempty"`
	ResponseID    string                 `protobuf:"bytes,6,opt,name=responseID,proto3" json:"responseID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPhoneRelayResponse) Reset() {
	*x = RegisterPhoneRelayResponse{}
	mi := &file_authentication_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPhoneRelayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPhoneRelayResponse) ProtoMessage() {}

func (x *RegisterPhoneRelayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPhoneRelayResponse.ProtoReflect.Descriptor instead.
func (*RegisterPhoneRelayResponse) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{15}
}

func (x *RegisterPhoneRelayResponse) GetCoordinates() *CoordinateMessage {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

func (x *RegisterPhoneRelayResponse) GetBrowser() *Device {
	if x != nil {
		return x.Browser
	}
	return nil
}

func (x *RegisterPhoneRelayResponse) GetPairingKey() []byte {
	if x != nil {
		return x.PairingKey
	}
	return nil
}

func (x *RegisterPhoneRelayResponse) GetValidFor() int64 {
	if x != nil {
		return x.ValidFor
	}
	return 0
}

func (x *RegisterPhoneRelayResponse) GetAuthKeyData() *TokenData {
	if x != nil {
		return x.AuthKeyData
	}
	return nil
}

func (x *RegisterPhoneRelayResponse) GetResponseID() string {
	if x != nil {
		return x.ResponseID
	}
	return ""
}

type CoordinateMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coord1        int64                  `protobuf:"varint,2,opt,name=coord1,proto3" json:"coord1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinateMessage) Reset() {
	*x = CoordinateMessage{}
	mi := &file_authentication_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinateMessage) ProtoMessage() {}

func (x *CoordinateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinateMessage.ProtoReflect.Descriptor instead.
func (*CoordinateMessage) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{16}
}

func (x *CoordinateMessage) GetCoord1() int64 {
	if x != nil {
		return x.Coord1
	}
	return 0
}

type RefreshPhoneRelayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coordinates   *CoordinateMessage     `protobuf:"bytes,1,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	PairKey       []byte                 `protobuf:"bytes,2,opt,name=pairKey,proto3" json:"pairKey,omitempty"`
	ValidFor      int64                  `protobuf:"varint,3,opt,name=validFor,proto3" json:"validFor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshPhoneRelayResponse) Reset() {
	*x = RefreshPhoneRelayResponse{}
	mi := &file_authentication_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshPhoneRelayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshPhoneRelayResponse) ProtoMessage() {}

func (x *RefreshPhoneRelayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshPhoneRelayResponse.ProtoReflect.Descriptor instead.
func (*RefreshPhoneRelayResponse) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{17}
}

func (x *RefreshPhoneRelayResponse) GetCoordinates() *CoordinateMessage {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

func (x *RefreshPhoneRelayResponse) GetPairKey() []byte {
	if x != nil {
		return x.PairKey
	}
	return nil
}

func (x *RefreshPhoneRelayResponse) GetValidFor() int64 {
	if x != nil {
		return x.ValidFor
	}
	return 0
}

type WebEncryptionKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coordinates   *CoordinateMessage     `protobuf:"bytes,1,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebEncryptionKeyResponse) Reset() {
	*x = WebEncryptionKeyResponse{}
	mi := &file_authentication_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebEncryptionKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebEncryptionKeyResponse) ProtoMessage() {}

func (x *WebEncryptionKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebEncryptionKeyResponse.ProtoReflect.Descriptor instead.
func (*WebEncryptionKeyResponse) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{18}
}

func (x *WebEncryptionKeyResponse) GetCoordinates() *CoordinateMessage {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

func (x *WebEncryptionKeyResponse) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type ErrorResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Type          int64                       `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"` // 5?
	Message       string                      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Class         []*ErrorResponse_ErrorClass `protobuf:"bytes,3,rep,name=class,proto3" json:"class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_authentication_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{19}
}

func (x *ErrorResponse) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorResponse) GetClass() []*ErrorResponse_ErrorClass {
	if x != nil {
		return x.Class
	}
	return nil
}

type ECDSAKeys struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field1        int64                  `protobuf:"varint,1,opt,name=field1,proto3" json:"field1,omitempty"` // idk?
	EncryptedKeys []byte                 `protobuf:"bytes,2,opt,name=encryptedKeys,proto3" json:"encryptedKeys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ECDSAKeys) Reset() {
	*x = ECDSAKeys{}
	mi := &file_authentication_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ECDSAKeys) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECDSAKeys) ProtoMessage() {}

func (x *ECDSAKeys) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECDSAKeys.ProtoReflect.Descriptor instead.
func (*ECDSAKeys) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{20}
}

func (x *ECDSAKeys) GetField1() int64 {
	if x != nil {
		return x.Field1
	}
	return 0
}

func (x *ECDSAKeys) GetEncryptedKeys() []byte {
	if x != nil {
		return x.EncryptedKeys
	}
	return nil
}

type CurrentDeviceData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Browser       *Device                `protobuf:"bytes,1,opt,name=browser,proto3" json:"browser,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentDeviceData) Reset() {
	*x = CurrentDeviceData{}
	mi := &file_authentication_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentDeviceData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentDeviceData) ProtoMessage() {}

func (x *CurrentDeviceData) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentDeviceData.ProtoReflect.Descriptor instead.
func (*CurrentDeviceData) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{21}
}

func (x *CurrentDeviceData) GetBrowser() *Device {
	if x != nil {
		return x.Browser
	}
	return nil
}

type KeyData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Mobile         *Device                `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	EcdsaKeys      *ECDSAKeys             `protobuf:"bytes,6,opt,name=ecdsaKeys,proto3" json:"ecdsaKeys,omitempty"`
	WebAuthKeyData *WebAuthKey            `protobuf:"bytes,2,opt,name=webAuthKeyData,proto3" json:"webAuthKeyData,omitempty"`
	Browser        *Device                `protobuf:"bytes,3,opt,name=browser,proto3" json:"browser,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KeyData) Reset() {
	*x = KeyData{}
	mi := &file_authentication_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyData) ProtoMessage() {}

func (x *KeyData) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyData.ProtoReflect.Descriptor instead.
func (*KeyData) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{22}
}

func (x *KeyData) GetMobile() *Device {
	if x != nil {
		return x.Mobile
	}
	return nil
}

func (x *KeyData) GetEcdsaKeys() *ECDSAKeys {
	if x != nil {
		return x.EcdsaKeys
	}
	return nil
}

func (x *KeyData) GetWebAuthKeyData() *WebAuthKey {
	if x != nil {
		return x.WebAuthKeyData
	}
	return nil
}

func (x *KeyData) GetBrowser() *Device {
	if x != nil {
		return x.Browser
	}
	return nil
}

type WebAuthKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WebAuthKey    []byte                 `protobuf:"bytes,1,opt,name=webAuthKey,proto3" json:"webAuthKey,omitempty"`
	ValidFor      int64                  `protobuf:"varint,2,opt,name=validFor,proto3" json:"validFor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebAuthKey) Reset() {
	*x = WebAuthKey{}
	mi := &file_authentication_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebAuthKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebAuthKey) ProtoMessage() {}

func (x *WebAuthKey) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebAuthKey.ProtoReflect.Descriptor instead.
func (*WebAuthKey) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{23}
}

func (x *WebAuthKey) GetWebAuthKey() []byte {
	if x != nil {
		return x.WebAuthKey
	}
	return nil
}

func (x *WebAuthKey) GetValidFor() int64 {
	if x != nil {
		return x.ValidFor
	}
	return 0
}

type URLData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PairingKey    []byte                 `protobuf:"bytes,1,opt,name=pairingKey,proto3" json:"pairingKey,omitempty"`
	AESKey        []byte                 `protobuf:"bytes,2,opt,name=AESKey,proto3" json:"AESKey,omitempty"`
	HMACKey       []byte                 `protobuf:"bytes,3,opt,name=HMACKey,proto3" json:"HMACKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *URLData) Reset() {
	*x = URLData{}
	mi := &file_authentication_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *URLData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*URLData) ProtoMessage() {}

func (x *URLData) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use URLData.ProtoReflect.Descriptor instead.
func (*URLData) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{24}
}

func (x *URLData) GetPairingKey() []byte {
	if x != nil {
		return x.PairingKey
	}
	return nil
}

func (x *URLData) GetAESKey() []byte {
	if x != nil {
		return x.AESKey
	}
	return nil
}

func (x *URLData) GetHMACKey() []byte {
	if x != nil {
		return x.HMACKey
	}
	return nil
}

type TokenData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TachyonAuthToken []byte                 `protobuf:"bytes,1,opt,name=tachyonAuthToken,proto3" json:"tachyonAuthToken,omitempty"`
	TTL              int64                  `protobuf:"varint,2,opt,name=TTL,proto3" json:"TTL,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TokenData) Reset() {
	*x = TokenData{}
	mi := &file_authentication_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenData) ProtoMessage() {}

func (x *TokenData) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenData.ProtoReflect.Descriptor instead.
func (*TokenData) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{25}
}

func (x *TokenData) GetTachyonAuthToken() []byte {
	if x != nil {
		return x.TachyonAuthToken
	}
	return nil
}

func (x *TokenData) GetTTL() int64 {
	if x != nil {
		return x.TTL
	}
	return 0
}

type PairedData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        *Device                `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	TokenData     *TokenData             `protobuf:"bytes,2,opt,name=tokenData,proto3" json:"tokenData,omitempty"`
	Browser       *Device                `protobuf:"bytes,3,opt,name=browser,proto3" json:"browser,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairedData) Reset() {
	*x = PairedData{}
	mi := &file_authentication_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairedData) ProtoMessage() {}

func (x *PairedData) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairedData.ProtoReflect.Descriptor instead.
func (*PairedData) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{26}
}

func (x *PairedData) GetMobile() *Device {
	if x != nil {
		return x.Mobile
	}
	return nil
}

func (x *PairedData) GetTokenData() *TokenData {
	if x != nil {
		return x.TokenData
	}
	return nil
}

func (x *PairedData) GetBrowser() *Device {
	if x != nil {
		return x.Browser
	}
	return nil
}

type RevokePairData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RevokedDevice *Device                `protobuf:"bytes,1,opt,name=revokedDevice,proto3" json:"revokedDevice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokePairData) Reset() {
	*x = RevokePairData{}
	mi := &file_authentication_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokePairData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokePairData) ProtoMessage() {}

func (x *RevokePairData) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokePairData.ProtoReflect.Descriptor instead.
func (*RevokePairData) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{27}
}

func (x *RevokePairData) GetRevokedDevice() *Device {
	if x != nil {
		return x.RevokedDevice
	}
	return nil
}

type SignInGaiaRequest_Inner struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	DeviceID      *SignInGaiaRequest_Inner_DeviceID `protobuf:"bytes,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	SomeData      *SignInGaiaRequest_Inner_Data     `protobuf:"bytes,36,opt,name=someData,proto3" json:"someData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInGaiaRequest_Inner) Reset() {
	*x = SignInGaiaRequest_Inner{}
	mi := &file_authentication_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInGaiaRequest_Inner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInGaiaRequest_Inner) ProtoMessage() {}

func (x *SignInGaiaRequest_Inner) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInGaiaRequest_Inner.ProtoReflect.Descriptor instead.
func (*SignInGaiaRequest_Inner) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{3, 0}
}

func (x *SignInGaiaRequest_Inner) GetDeviceID() *SignInGaiaRequest_Inner_DeviceID {
	if x != nil {
		return x.DeviceID
	}
	return nil
}

func (x *SignInGaiaRequest_Inner) GetSomeData() *SignInGaiaRequest_Inner_Data {
	if x != nil {
		return x.SomeData
	}
	return nil
}

type SignInGaiaRequest_Inner_DeviceID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnknownInt1   int32                  `protobuf:"varint,1,opt,name=unknownInt1,proto3" json:"unknownInt1,omitempty"` // 3
	DeviceID      string                 `protobuf:"bytes,2,opt,name=deviceID,proto3" json:"deviceID,omitempty"`        // messages-web-{uuid without dashes}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInGaiaRequest_Inner_DeviceID) Reset() {
	*x = SignInGaiaRequest_Inner_DeviceID{}
	mi := &file_authentication_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInGaiaRequest_Inner_DeviceID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInGaiaRequest_Inner_DeviceID) ProtoMessage() {}

func (x *SignInGaiaRequest_Inner_DeviceID) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInGaiaRequest_Inner_DeviceID.ProtoReflect.Descriptor instead.
func (*SignInGaiaRequest_Inner_DeviceID) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{3, 0, 0}
}

func (x *SignInGaiaRequest_Inner_DeviceID) GetUnknownInt1() int32 {
	if x != nil {
		return x.UnknownInt1
	}
	return 0
}

func (x *SignInGaiaRequest_Inner_DeviceID) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

type SignInGaiaRequest_Inner_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SomeData      []byte                 `protobuf:"bytes,3,opt,name=someData,proto3" json:"someData,omitempty"` // maybe an encryption key?
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInGaiaRequest_Inner_Data) Reset() {
	*x = SignInGaiaRequest_Inner_Data{}
	mi := &file_authentication_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInGaiaRequest_Inner_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInGaiaRequest_Inner_Data) ProtoMessage() {}

func (x *SignInGaiaRequest_Inner_Data) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInGaiaRequest_Inner_Data.ProtoReflect.Descriptor instead.
func (*SignInGaiaRequest_Inner_Data) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{3, 0, 1}
}

func (x *SignInGaiaRequest_Inner_Data) GetSomeData() []byte {
	if x != nil {
		return x.SomeData
	}
	return nil
}

type SignInGaiaResponse_Header struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UnknownInt2      uint64                 `protobuf:"varint,2,opt,name=unknownInt2,proto3" json:"unknownInt2,omitempty"`
	UnknownTimestamp int64                  `protobuf:"varint,4,opt,name=unknownTimestamp,proto3" json:"unknownTimestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SignInGaiaResponse_Header) Reset() {
	*x = SignInGaiaResponse_Header{}
	mi := &file_authentication_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInGaiaResponse_Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInGaiaResponse_Header) ProtoMessage() {}

func (x *SignInGaiaResponse_Header) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInGaiaResponse_Header.ProtoReflect.Descriptor instead.
func (*SignInGaiaResponse_Header) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{4, 0}
}

func (x *SignInGaiaResponse_Header) GetUnknownInt2() uint64 {
	if x != nil {
		return x.UnknownInt2
	}
	return 0
}

func (x *SignInGaiaResponse_Header) GetUnknownTimestamp() int64 {
	if x != nil {
		return x.UnknownTimestamp
	}
	return 0
}

type SignInGaiaResponse_DeviceData struct {
	state         protoimpl.MessageState                       `protogen:"open.v1"`
	DeviceWrapper *SignInGaiaResponse_DeviceData_DeviceWrapper `protobuf:"bytes,1,opt,name=deviceWrapper,proto3" json:"deviceWrapper,omitempty"`
	UnknownItems2 []*RPCGaiaData_UnknownContainer_Item2_Item1  `protobuf:"bytes,2,rep,name=unknownItems2,proto3" json:"unknownItems2,omitempty"`
	UnknownItems3 []*RPCGaiaData_UnknownContainer_Item4        `protobuf:"bytes,3,rep,name=unknownItems3,proto3" json:"unknownItems3,omitempty"` // index 4 is some unknown field with no real data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInGaiaResponse_DeviceData) Reset() {
	*x = SignInGaiaResponse_DeviceData{}
	mi := &file_authentication_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInGaiaResponse_DeviceData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInGaiaResponse_DeviceData) ProtoMessage() {}

func (x *SignInGaiaResponse_DeviceData) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInGaiaResponse_DeviceData.ProtoReflect.Descriptor instead.
func (*SignInGaiaResponse_DeviceData) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{4, 1}
}

func (x *SignInGaiaResponse_DeviceData) GetDeviceWrapper() *SignInGaiaResponse_DeviceData_DeviceWrapper {
	if x != nil {
		return x.DeviceWrapper
	}
	return nil
}

func (x *SignInGaiaResponse_DeviceData) GetUnknownItems2() []*RPCGaiaData_UnknownContainer_Item2_Item1 {
	if x != nil {
		return x.UnknownItems2
	}
	return nil
}

func (x *SignInGaiaResponse_DeviceData) GetUnknownItems3() []*RPCGaiaData_UnknownContainer_Item4 {
	if x != nil {
		return x.UnknownItems3
	}
	return nil
}

type SignInGaiaResponse_DeviceData_DeviceWrapper struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *Device                `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInGaiaResponse_DeviceData_DeviceWrapper) Reset() {
	*x = SignInGaiaResponse_DeviceData_DeviceWrapper{}
	mi := &file_authentication_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInGaiaResponse_DeviceData_DeviceWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInGaiaResponse_DeviceData_DeviceWrapper) ProtoMessage() {}

func (x *SignInGaiaResponse_DeviceData_DeviceWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInGaiaResponse_DeviceData_DeviceWrapper.ProtoReflect.Descriptor instead.
func (*SignInGaiaResponse_DeviceData_DeviceWrapper) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{4, 1, 0}
}

func (x *SignInGaiaResponse_DeviceData_DeviceWrapper) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

type RPCGaiaData_UnknownContainer struct {
	state                        protoimpl.MessageState                `protogen:"open.v1"`
	Item2                        *RPCGaiaData_UnknownContainer_Item2   `protobuf:"bytes,2,opt,name=item2,proto3" json:"item2,omitempty"`
	UnknownTimestampMicroseconds int64                                 `protobuf:"varint,3,opt,name=unknownTimestampMicroseconds,proto3" json:"unknownTimestampMicroseconds,omitempty"` // pairing timestamp?
	Item4                        []*RPCGaiaData_UnknownContainer_Item4 `protobuf:"bytes,4,rep,name=item4,proto3" json:"item4,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *RPCGaiaData_UnknownContainer) Reset() {
	*x = RPCGaiaData_UnknownContainer{}
	mi := &file_authentication_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPCGaiaData_UnknownContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCGaiaData_UnknownContainer) ProtoMessage() {}

func (x *RPCGaiaData_UnknownContainer) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCGaiaData_UnknownContainer.ProtoReflect.Descriptor instead.
func (*RPCGaiaData_UnknownContainer) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{8, 0}
}

func (x *RPCGaiaData_UnknownContainer) GetItem2() *RPCGaiaData_UnknownContainer_Item2 {
	if x != nil {
		return x.Item2
	}
	return nil
}

func (x *RPCGaiaData_UnknownContainer) GetUnknownTimestampMicroseconds() int64 {
	if x != nil {
		return x.UnknownTimestampMicroseconds
	}
	return 0
}

func (x *RPCGaiaData_UnknownContainer) GetItem4() []*RPCGaiaData_UnknownContainer_Item4 {
	if x != nil {
		return x.Item4
	}
	return nil
}

type RPCGaiaData_UnknownContainer_Item2 struct {
	state         protoimpl.MessageState                      `protogen:"open.v1"`
	Item1         []*RPCGaiaData_UnknownContainer_Item2_Item1 `protobuf:"bytes,1,rep,name=item1,proto3" json:"item1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPCGaiaData_UnknownContainer_Item2) Reset() {
	*x = RPCGaiaData_UnknownContainer_Item2{}
	mi := &file_authentication_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPCGaiaData_UnknownContainer_Item2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCGaiaData_UnknownContainer_Item2) ProtoMessage() {}

func (x *RPCGaiaData_UnknownContainer_Item2) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCGaiaData_UnknownContainer_Item2.ProtoReflect.Descriptor instead.
func (*RPCGaiaData_UnknownContainer_Item2) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{8, 0, 0}
}

func (x *RPCGaiaData_UnknownContainer_Item2) GetItem1() []*RPCGaiaData_UnknownContainer_Item2_Item1 {
	if x != nil {
		return x.Item1
	}
	return nil
}

type RPCGaiaData_UnknownContainer_Item4 struct {
	state                        protoimpl.MessageState                    `protogen:"open.v1"`
	DestOrSourceUUID             string                                    `protobuf:"bytes,1,opt,name=destOrSourceUUID,proto3" json:"destOrSourceUUID,omitempty"`
	UnknownInt3                  int32                                     `protobuf:"varint,3,opt,name=unknownInt3,proto3" json:"unknownInt3,omitempty"`                                   // 1 for destination device, 6 for local device?
	UnknownInt4                  int32                                     `protobuf:"varint,4,opt,name=unknownInt4,proto3" json:"unknownInt4,omitempty"`                                   // always 6?
	UnknownTimestampMicroseconds int64                                     `protobuf:"varint,7,opt,name=unknownTimestampMicroseconds,proto3" json:"unknownTimestampMicroseconds,omitempty"` // maybe device creation ts?
	Item8                        *RPCGaiaData_UnknownContainer_Item4_Item8 `protobuf:"bytes,8,opt,name=item8,proto3" json:"item8,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *RPCGaiaData_UnknownContainer_Item4) Reset() {
	*x = RPCGaiaData_UnknownContainer_Item4{}
	mi := &file_authentication_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPCGaiaData_UnknownContainer_Item4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCGaiaData_UnknownContainer_Item4) ProtoMessage() {}

func (x *RPCGaiaData_UnknownContainer_Item4) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCGaiaData_UnknownContainer_Item4.ProtoReflect.Descriptor instead.
func (*RPCGaiaData_UnknownContainer_Item4) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{8, 0, 1}
}

func (x *RPCGaiaData_UnknownContainer_Item4) GetDestOrSourceUUID() string {
	if x != nil {
		return x.DestOrSourceUUID
	}
	return ""
}

func (x *RPCGaiaData_UnknownContainer_Item4) GetUnknownInt3() int32 {
	if x != nil {
		return x.UnknownInt3
	}
	return 0
}

func (x *RPCGaiaData_UnknownContainer_Item4) GetUnknownInt4() int32 {
	if x != nil {
		return x.UnknownInt4
	}
	return 0
}

func (x *RPCGaiaData_UnknownContainer_Item4) GetUnknownTimestampMicroseconds() int64 {
	if x != nil {
		return x.UnknownTimestampMicroseconds
	}
	return 0
}

func (x *RPCGaiaData_UnknownContainer_Item4) GetItem8() *RPCGaiaData_UnknownContainer_Item4_Item8 {
	if x != nil {
		return x.Item8
	}
	return nil
}

type RPCGaiaData_UnknownContainer_Item2_Item1 struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DestOrSourceUUID string                 `protobuf:"bytes,1,opt,name=destOrSourceUUID,proto3" json:"destOrSourceUUID,omitempty"`
	UnknownInt4      int32                  `protobuf:"varint,4,opt,name=unknownInt4,proto3" json:"unknownInt4,omitempty"` // 1 for destination device, 6 for local device?
	LanguageCode     string                 `protobuf:"bytes,5,opt,name=languageCode,proto3" json:"languageCode,omitempty"`
	UnknownBigInt7   uint64                 `protobuf:"varint,7,opt,name=unknownBigInt7,proto3" json:"unknownBigInt7,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RPCGaiaData_UnknownContainer_Item2_Item1) Reset() {
	*x = RPCGaiaData_UnknownContainer_Item2_Item1{}
	mi := &file_authentication_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPCGaiaData_UnknownContainer_Item2_Item1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCGaiaData_UnknownContainer_Item2_Item1) ProtoMessage() {}

func (x *RPCGaiaData_UnknownContainer_Item2_Item1) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCGaiaData_UnknownContainer_Item2_Item1.ProtoReflect.Descriptor instead.
func (*RPCGaiaData_UnknownContainer_Item2_Item1) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{8, 0, 0, 0}
}

func (x *RPCGaiaData_UnknownContainer_Item2_Item1) GetDestOrSourceUUID() string {
	if x != nil {
		return x.DestOrSourceUUID
	}
	return ""
}

func (x *RPCGaiaData_UnknownContainer_Item2_Item1) GetUnknownInt4() int32 {
	if x != nil {
		return x.UnknownInt4
	}
	return 0
}

func (x *RPCGaiaData_UnknownContainer_Item2_Item1) GetLanguageCode() string {
	if x != nil {
		return x.LanguageCode
	}
	return ""
}

func (x *RPCGaiaData_UnknownContainer_Item2_Item1) GetUnknownBigInt7() uint64 {
	if x != nil {
		return x.UnknownBigInt7
	}
	return 0
}

type RPCGaiaData_UnknownContainer_Item4_Item8 struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UnknownInt1      int32                  `protobuf:"varint,1,opt,name=unknownInt1,proto3" json:"unknownInt1,omitempty"`           // present for destination device?
	UnknownTimestamp int32                  `protobuf:"varint,2,opt,name=unknownTimestamp,proto3" json:"unknownTimestamp,omitempty"` // present for destination device?
	UnknownBytes     []byte                 `protobuf:"bytes,3,opt,name=unknownBytes,proto3" json:"unknownBytes,omitempty"`          // present for local device?
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RPCGaiaData_UnknownContainer_Item4_Item8) Reset() {
	*x = RPCGaiaData_UnknownContainer_Item4_Item8{}
	mi := &file_authentication_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPCGaiaData_UnknownContainer_Item4_Item8) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCGaiaData_UnknownContainer_Item4_Item8) ProtoMessage() {}

func (x *RPCGaiaData_UnknownContainer_Item4_Item8) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCGaiaData_UnknownContainer_Item4_Item8.ProtoReflect.Descriptor instead.
func (*RPCGaiaData_UnknownContainer_Item4_Item8) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{8, 0, 1, 0}
}

func (x *RPCGaiaData_UnknownContainer_Item4_Item8) GetUnknownInt1() int32 {
	if x != nil {
		return x.UnknownInt1
	}
	return 0
}

func (x *RPCGaiaData_UnknownContainer_Item4_Item8) GetUnknownTimestamp() int32 {
	if x != nil {
		return x.UnknownTimestamp
	}
	return 0
}

func (x *RPCGaiaData_UnknownContainer_Item4_Item8) GetUnknownBytes() []byte {
	if x != nil {
		return x.UnknownBytes
	}
	return nil
}

type RegisterRefreshRequest_NestedEmptyArr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmptyArr      *EmptyArr              `protobuf:"bytes,9,opt,name=emptyArr,proto3" json:"emptyArr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRefreshRequest_NestedEmptyArr) Reset() {
	*x = RegisterRefreshRequest_NestedEmptyArr{}
	mi := &file_authentication_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRefreshRequest_NestedEmptyArr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRefreshRequest_NestedEmptyArr) ProtoMessage() {}

func (x *RegisterRefreshRequest_NestedEmptyArr) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRefreshRequest_NestedEmptyArr.ProtoReflect.Descriptor instead.
func (*RegisterRefreshRequest_NestedEmptyArr) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{13, 0}
}

func (x *RegisterRefreshRequest_NestedEmptyArr) GetEmptyArr() *EmptyArr {
	if x != nil {
		return x.EmptyArr
	}
	return nil
}

type ErrorResponse_ErrorClass struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Class         string                 `protobuf:"bytes,1,opt,name=class,proto3" json:"class,omitempty"` // 2: {1: 1}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse_ErrorClass) Reset() {
	*x = ErrorResponse_ErrorClass{}
	mi := &file_authentication_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse_ErrorClass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse_ErrorClass) ProtoMessage() {}

func (x *ErrorResponse_ErrorClass) ProtoReflect() protoreflect.Message {
	mi := &file_authentication_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse_ErrorClass.ProtoReflect.Descriptor instead.
func (*ErrorResponse_ErrorClass) Descriptor() ([]byte, []int) {
	return file_authentication_proto_rawDescGZIP(), []int{19, 0}
}

func (x *ErrorResponse_ErrorClass) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

var File_authentication_proto protoreflect.FileDescriptor

const file_authentication_proto_rawDesc = "" +
	"\n" +
	"\x14authentication.proto\x12\x0eauthentication\x1a\n" +
	"util.proto\x1a\x13vendor/pblite.proto\"\xb9\x01\n" +
	"\x0eBrowserDetails\x12\x1c\n" +
	"\tuserAgent\x18\x01 \x01(\tR\tuserAgent\x12=\n" +
	"\vbrowserType\x18\x02 \x01(\x0e2\x1b.authentication.BrowserTypeR\vbrowserType\x12\x0e\n" +
	"\x02OS\x18\x03 \x01(\tR\x02OS\x12:\n" +
	"\n" +
	"deviceType\x18\x06 \x01(\x0e2\x1a.authentication.DeviceTypeR\n" +
	"deviceType\"V\n" +
	"\x06Device\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x03R\x06userID\x12\x1a\n" +
	"\bsourceID\x18\x02 \x01(\tR\bsourceID\x12\x18\n" +
	"\anetwork\x18\x03 \x01(\tR\anetwork\"k\n" +
	"\rConfigVersion\x12\x12\n" +
	"\x04Year\x18\x03 \x01(\x05R\x04Year\x12\x14\n" +
	"\x05Month\x18\x04 \x01(\x05R\x05Month\x12\x10\n" +
	"\x03Day\x18\x05 \x01(\x05R\x03Day\x12\x0e\n" +
	"\x02V1\x18\a \x01(\x05R\x02V1\x12\x0e\n" +
	"\x02V2\x18\t \x01(\x05R\x02V2\"\xe3\x03\n" +
	"\x11SignInGaiaRequest\x12=\n" +
	"\vauthMessage\x18\x01 \x01(\v2\x1b.authentication.AuthMessageR\vauthMessage\x12=\n" +
	"\x05inner\x18\x02 \x01(\v2'.authentication.SignInGaiaRequest.InnerR\x05inner\x12 \n" +
	"\vunknownInt3\x18\x03 \x01(\x05R\vunknownInt3\x12\x18\n" +
	"\anetwork\x18\x04 \x01(\tR\anetwork\x1a\x93\x02\n" +
	"\x05Inner\x12L\n" +
	"\bdeviceID\x18\x01 \x01(\v20.authentication.SignInGaiaRequest.Inner.DeviceIDR\bdeviceID\x12N\n" +
	"\bsomeData\x18$ \x01(\v2,.authentication.SignInGaiaRequest.Inner.DataB\x04\x80\xb5\x18\x01R\bsomeData\x1aH\n" +
	"\bDeviceID\x12 \n" +
	"\vunknownInt1\x18\x01 \x01(\x05R\vunknownInt1\x12\x1a\n" +
	"\bdeviceID\x18\x02 \x01(\tR\bdeviceID\x1a\"\n" +
	"\x04Data\x12\x1a\n" +
	"\bsomeData\x18\x03 \x01(\fR\bsomeData\"\xd6\x05\n" +
	"\x12SignInGaiaResponse\x12A\n" +
	"\x06header\x18\x01 \x01(\v2).authentication.SignInGaiaResponse.HeaderR\x06header\x120\n" +
	"\x10maybeBrowserUUID\x18\x02 \x01(\tB\x04\x80\xb5\x18\x01R\x10maybeBrowserUUID\x12M\n" +
	"\n" +
	"deviceData\x18\x03 \x01(\v2-.authentication.SignInGaiaResponse.DeviceDataR\n" +
	"deviceData\x127\n" +
	"\ttokenData\x18\x04 \x01(\v2\x19.authentication.TokenDataR\ttokenData\x1aV\n" +
	"\x06Header\x12 \n" +
	"\vunknownInt2\x18\x02 \x01(\x04R\vunknownInt2\x12*\n" +
	"\x10unknownTimestamp\x18\x04 \x01(\x03R\x10unknownTimestamp\x1a\xea\x02\n" +
	"\n" +
	"DeviceData\x12a\n" +
	"\rdeviceWrapper\x18\x01 \x01(\v2;.authentication.SignInGaiaResponse.DeviceData.DeviceWrapperR\rdeviceWrapper\x12^\n" +
	"\runknownItems2\x18\x02 \x03(\v28.authentication.RPCGaiaData.UnknownContainer.Item2.Item1R\runknownItems2\x12X\n" +
	"\runknownItems3\x18\x03 \x03(\v22.authentication.RPCGaiaData.UnknownContainer.Item4R\runknownItems3\x1a?\n" +
	"\rDeviceWrapper\x12.\n" +
	"\x06device\x18\x01 \x01(\v2\x16.authentication.DeviceR\x06device\"\xdb\x02\n" +
	"\x1bGaiaPairingRequestContainer\x12*\n" +
	"\x10pairingAttemptID\x18\x01 \x01(\tR\x10pairingAttemptID\x12F\n" +
	"\x0ebrowserDetails\x18\x02 \x01(\v2\x1e.authentication.BrowserDetailsR\x0ebrowserDetails\x12&\n" +
	"\x0estartTimestamp\x18\x03 \x01(\x03R\x0estartTimestamp\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12H\n" +
	"\x1fproposedVerificationCodeVersion\x18\x05 \x01(\x05R\x1fproposedVerificationCodeVersion\x12B\n" +
	"\x1cproposedKeyDerivationVersion\x18\x06 \x01(\x05R\x1cproposedKeyDerivationVersion\"\xdc\x02\n" +
	"\x1cGaiaPairingResponseContainer\x12(\n" +
	"\x0ffinishErrorType\x18\x01 \x01(\x05R\x0ffinishErrorType\x12(\n" +
	"\x0ffinishErrorCode\x18\x02 \x01(\x05R\x0ffinishErrorCode\x12 \n" +
	"\vunknownInt3\x18\x03 \x01(\x05R\vunknownInt3\x12 \n" +
	"\vsessionUUID\x18\x04 \x01(\tR\vsessionUUID\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12J\n" +
	" confirmedVerificationCodeVersion\x18\x06 \x01(\x05R confirmedVerificationCodeVersion\x12D\n" +
	"\x1dconfirmedKeyDerivationVersion\x18\a \x01(\x05R\x1dconfirmedKeyDerivationVersion\"F\n" +
	"\x18RevokeGaiaPairingRequest\x12*\n" +
	"\x10pairingAttemptID\x18\x01 \x01(\tR\x10pairingAttemptID\"\x85\b\n" +
	"\vRPCGaiaData\x12\x18\n" +
	"\acommand\x18\x01 \x01(\x05R\acommand\x12V\n" +
	"\x0fmaybeServerData\x18l \x01(\v2,.authentication.RPCGaiaData.UnknownContainerR\x0fmaybeServerData\x1a\x83\a\n" +
	"\x10UnknownContainer\x12H\n" +
	"\x05item2\x18\x02 \x01(\v22.authentication.RPCGaiaData.UnknownContainer.Item2R\x05item2\x12B\n" +
	"\x1cunknownTimestampMicroseconds\x18\x03 \x01(\x03R\x1cunknownTimestampMicroseconds\x12H\n" +
	"\x05item4\x18\x04 \x03(\v22.authentication.RPCGaiaData.UnknownContainer.Item4R\x05item4\x1a\x81\x02\n" +
	"\x05Item2\x12N\n" +
	"\x05item1\x18\x01 \x03(\v28.authentication.RPCGaiaData.UnknownContainer.Item2.Item1R\x05item1\x1a\xa7\x01\n" +
	"\x05Item1\x120\n" +
	"\x10destOrSourceUUID\x18\x01 \x01(\tB\x04\x80\xb5\x18\x01R\x10destOrSourceUUID\x12 \n" +
	"\vunknownInt4\x18\x04 \x01(\x05R\vunknownInt4\x12\"\n" +
	"\flanguageCode\x18\x05 \x01(\tR\flanguageCode\x12&\n" +
	"\x0eunknownBigInt7\x18\a \x01(\x04R\x0eunknownBigInt7\x1a\x92\x03\n" +
	"\x05Item4\x120\n" +
	"\x10destOrSourceUUID\x18\x01 \x01(\tB\x04\x80\xb5\x18\x01R\x10destOrSourceUUID\x12 \n" +
	"\vunknownInt3\x18\x03 \x01(\x05R\vunknownInt3\x12 \n" +
	"\vunknownInt4\x18\x04 \x01(\x05R\vunknownInt4\x12B\n" +
	"\x1cunknownTimestampMicroseconds\x18\a \x01(\x03R\x1cunknownTimestampMicroseconds\x12T\n" +
	"\x05item8\x18\b \x01(\v28.authentication.RPCGaiaData.UnknownContainer.Item4.Item8B\x04\x80\xb5\x18\x01R\x05item8\x1ay\n" +
	"\x05Item8\x12 \n" +
	"\vunknownInt1\x18\x01 \x01(\x05R\vunknownInt1\x12*\n" +
	"\x10unknownTimestamp\x18\x02 \x01(\x05R\x10unknownTimestamp\x12\"\n" +
	"\funknownBytes\x18\x03 \x01(\fR\funknownBytes\"\xa2\x02\n" +
	"\x17AuthenticationContainer\x12=\n" +
	"\vauthMessage\x18\x01 \x01(\v2\x1b.authentication.AuthMessageR\vauthMessage\x12F\n" +
	"\x0ebrowserDetails\x18\x03 \x01(\v2\x1e.authentication.BrowserDetailsR\x0ebrowserDetails\x123\n" +
	"\akeyData\x18\x04 \x01(\v2\x17.authentication.KeyDataH\x00R\akeyData\x12C\n" +
	"\n" +
	"deviceData\x18\x05 \x01(\v2!.authentication.CurrentDeviceDataH\x00R\n" +
	"deviceDataB\x06\n" +
	"\x04data\"\xb6\x01\n" +
	"\vAuthMessage\x12\x1c\n" +
	"\trequestID\x18\x01 \x01(\tR\trequestID\x12\x18\n" +
	"\anetwork\x18\x03 \x01(\tR\anetwork\x12*\n" +
	"\x10tachyonAuthToken\x18\x06 \x01(\fR\x10tachyonAuthToken\x12C\n" +
	"\rconfigVersion\x18\a \x01(\v2\x1d.authentication.ConfigVersionR\rconfigVersion\"\x8c\x01\n" +
	"\x19RevokeRelayPairingRequest\x12=\n" +
	"\vauthMessage\x18\x01 \x01(\v2\x1b.authentication.AuthMessageR\vauthMessage\x120\n" +
	"\abrowser\x18\x02 \x01(\v2\x16.authentication.DeviceR\abrowser\"\x1c\n" +
	"\x1aRevokeRelayPairingResponse\"\xa2\x03\n" +
	"\x16RegisterRefreshRequest\x12=\n" +
	"\vmessageAuth\x18\x01 \x01(\v2\x1b.authentication.AuthMessageR\vmessageAuth\x12D\n" +
	"\x11currBrowserDevice\x18\x02 \x01(\v2\x16.authentication.DeviceR\x11currBrowserDevice\x12$\n" +
	"\runixTimestamp\x18\x03 \x01(\x03R\runixTimestamp\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\x12_\n" +
	"\x0femptyRefreshArr\x18\r \x01(\v25.authentication.RegisterRefreshRequest.NestedEmptyArrR\x0femptyRefreshArr\x12 \n" +
	"\vmessageType\x18\x10 \x01(\x05R\vmessageType\x1a<\n" +
	"\x0eNestedEmptyArr\x12*\n" +
	"\bemptyArr\x18\t \x01(\v2\x0e.util.EmptyArrR\bemptyArr\"R\n" +
	"\x17RegisterRefreshResponse\x127\n" +
	"\ttokenData\x18\x02 \x01(\v2\x19.authentication.TokenDataR\ttokenData\"\xac\x02\n" +
	"\x1aRegisterPhoneRelayResponse\x12C\n" +
	"\vcoordinates\x18\x01 \x01(\v2!.authentication.CoordinateMessageR\vcoordinates\x120\n" +
	"\abrowser\x18\x02 \x01(\v2\x16.authentication.DeviceR\abrowser\x12\x1e\n" +
	"\n" +
	"pairingKey\x18\x03 \x01(\fR\n" +
	"pairingKey\x12\x1a\n" +
	"\bvalidFor\x18\x04 \x01(\x03R\bvalidFor\x12;\n" +
	"\vauthKeyData\x18\x05 \x01(\v2\x19.authentication.TokenDataR\vauthKeyData\x12\x1e\n" +
	"\n" +
	"responseID\x18\x06 \x01(\tR\n" +
	"responseID\"+\n" +
	"\x11CoordinateMessage\x12\x16\n" +
	"\x06coord1\x18\x02 \x01(\x03R\x06coord1\"\x96\x01\n" +
	"\x19RefreshPhoneRelayResponse\x12C\n" +
	"\vcoordinates\x18\x01 \x01(\v2!.authentication.CoordinateMessageR\vcoordinates\x12\x18\n" +
	"\apairKey\x18\x02 \x01(\fR\apairKey\x12\x1a\n" +
	"\bvalidFor\x18\x03 \x01(\x03R\bvalidFor\"q\n" +
	"\x18WebEncryptionKeyResponse\x12C\n" +
	"\vcoordinates\x18\x01 \x01(\v2!.authentication.CoordinateMessageR\vcoordinates\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\"\xa1\x01\n" +
	"\rErrorResponse\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x03R\x04type\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12>\n" +
	"\x05class\x18\x03 \x03(\v2(.authentication.ErrorResponse.ErrorClassR\x05class\x1a\"\n" +
	"\n" +
	"ErrorClass\x12\x14\n" +
	"\x05class\x18\x01 \x01(\tR\x05class\"I\n" +
	"\tECDSAKeys\x12\x16\n" +
	"\x06field1\x18\x01 \x01(\x03R\x06field1\x12$\n" +
	"\rencryptedKeys\x18\x02 \x01(\fR\rencryptedKeys\"E\n" +
	"\x11CurrentDeviceData\x120\n" +
	"\abrowser\x18\x01 \x01(\v2\x16.authentication.DeviceR\abrowser\"\xe8\x01\n" +
	"\aKeyData\x12.\n" +
	"\x06mobile\x18\x01 \x01(\v2\x16.authentication.DeviceR\x06mobile\x127\n" +
	"\tecdsaKeys\x18\x06 \x01(\v2\x19.authentication.ECDSAKeysR\tecdsaKeys\x12B\n" +
	"\x0ewebAuthKeyData\x18\x02 \x01(\v2\x1a.authentication.WebAuthKeyR\x0ewebAuthKeyData\x120\n" +
	"\abrowser\x18\x03 \x01(\v2\x16.authentication.DeviceR\abrowser\"H\n" +
	"\n" +
	"WebAuthKey\x12\x1e\n" +
	"\n" +
	"webAuthKey\x18\x01 \x01(\fR\n" +
	"webAuthKey\x12\x1a\n" +
	"\bvalidFor\x18\x02 \x01(\x03R\bvalidFor\"[\n" +
	"\aURLData\x12\x1e\n" +
	"\n" +
	"pairingKey\x18\x01 \x01(\fR\n" +
	"pairingKey\x12\x16\n" +
	"\x06AESKey\x18\x02 \x01(\fR\x06AESKey\x12\x18\n" +
	"\aHMACKey\x18\x03 \x01(\fR\aHMACKey\"I\n" +
	"\tTokenData\x12*\n" +
	"\x10tachyonAuthToken\x18\x01 \x01(\fR\x10tachyonAuthToken\x12\x10\n" +
	"\x03TTL\x18\x02 \x01(\x03R\x03TTL\"\xa7\x01\n" +
	"\n" +
	"PairedData\x12.\n" +
	"\x06mobile\x18\x01 \x01(\v2\x16.authentication.DeviceR\x06mobile\x127\n" +
	"\ttokenData\x18\x02 \x01(\v2\x19.authentication.TokenDataR\ttokenData\x120\n" +
	"\abrowser\x18\x03 \x01(\v2\x16.authentication.DeviceR\abrowser\"N\n" +
	"\x0eRevokePairData\x12<\n" +
	"\rrevokedDevice\x18\x01 \x01(\v2\x16.authentication.DeviceR\rrevokedDevice*t\n" +
	"\vBrowserType\x12\x18\n" +
	"\x14UNKNOWN_BROWSER_TYPE\x10\x00\x12\t\n" +
	"\x05OTHER\x10\x01\x12\n" +
	"\n" +
	"\x06CHROME\x10\x02\x12\v\n" +
	"\aFIREFOX\x10\x03\x12\n" +
	"\n" +
	"\x06SAFARI\x10\x04\x12\t\n" +
	"\x05OPERA\x10\x05\x12\x06\n" +
	"\x02IE\x10\x06\x12\b\n" +
	"\x04EDGE\x10\a*C\n" +
	"\n" +
	"DeviceType\x12\x17\n" +
	"\x13UNKNOWN_DEVICE_TYPE\x10\x00\x12\a\n" +
	"\x03WEB\x10\x01\x12\n" +
	"\n" +
	"\x06TABLET\x10\x02\x12\a\n" +
	"\x03PWA\x10\x03B\fZ\n" +
	"../gmprotob\x06proto3"

var (
	file_authentication_proto_rawDescOnce sync.Once
	file_authentication_proto_rawDescData []byte
)

func file_authentication_proto_rawDescGZIP() []byte {
	file_authentication_proto_rawDescOnce.Do(func() {
		file_authentication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authentication_proto_rawDesc), len(file_authentication_proto_rawDesc)))
	})
	return file_authentication_proto_rawDescData
}

var file_authentication_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_authentication_proto_msgTypes = make([]protoimpl.MessageInfo, 41)
var file_authentication_proto_goTypes = []any{
	(BrowserType)(0),                                    // 0: authentication.BrowserType
	(DeviceType)(0),                                     // 1: authentication.DeviceType
	(*BrowserDetails)(nil),                              // 2: authentication.BrowserDetails
	(*Device)(nil),                                      // 3: authentication.Device
	(*ConfigVersion)(nil),                               // 4: authentication.ConfigVersion
	(*SignInGaiaRequest)(nil),                           // 5: authentication.SignInGaiaRequest
	(*SignInGaiaResponse)(nil),                          // 6: authentication.SignInGaiaResponse
	(*GaiaPairingRequestContainer)(nil),                 // 7: authentication.GaiaPairingRequestContainer
	(*GaiaPairingResponseContainer)(nil),                // 8: authentication.GaiaPairingResponseContainer
	(*RevokeGaiaPairingRequest)(nil),                    // 9: authentication.RevokeGaiaPairingRequest
	(*RPCGaiaData)(nil),                                 // 10: authentication.RPCGaiaData
	(*AuthenticationContainer)(nil),                     // 11: authentication.AuthenticationContainer
	(*AuthMessage)(nil),                                 // 12: authentication.AuthMessage
	(*RevokeRelayPairingRequest)(nil),                   // 13: authentication.RevokeRelayPairingRequest
	(*RevokeRelayPairingResponse)(nil),                  // 14: authentication.RevokeRelayPairingResponse
	(*RegisterRefreshRequest)(nil),                      // 15: authentication.RegisterRefreshRequest
	(*RegisterRefreshResponse)(nil),                     // 16: authentication.RegisterRefreshResponse
	(*RegisterPhoneRelayResponse)(nil),                  // 17: authentication.RegisterPhoneRelayResponse
	(*CoordinateMessage)(nil),                           // 18: authentication.CoordinateMessage
	(*RefreshPhoneRelayResponse)(nil),                   // 19: authentication.RefreshPhoneRelayResponse
	(*WebEncryptionKeyResponse)(nil),                    // 20: authentication.WebEncryptionKeyResponse
	(*ErrorResponse)(nil),                               // 21: authentication.ErrorResponse
	(*ECDSAKeys)(nil),                                   // 22: authentication.ECDSAKeys
	(*CurrentDeviceData)(nil),                           // 23: authentication.CurrentDeviceData
	(*KeyData)(nil),                                     // 24: authentication.KeyData
	(*WebAuthKey)(nil),                                  // 25: authentication.WebAuthKey
	(*URLData)(nil),                                     // 26: authentication.URLData
	(*TokenData)(nil),                                   // 27: authentication.TokenData
	(*PairedData)(nil),                                  // 28: authentication.PairedData
	(*RevokePairData)(nil),                              // 29: authentication.RevokePairData
	(*SignInGaiaRequest_Inner)(nil),                     // 30: authentication.SignInGaiaRequest.Inner
	(*SignInGaiaRequest_Inner_DeviceID)(nil),            // 31: authentication.SignInGaiaRequest.Inner.DeviceID
	(*SignInGaiaRequest_Inner_Data)(nil),                // 32: authentication.SignInGaiaRequest.Inner.Data
	(*SignInGaiaResponse_Header)(nil),                   // 33: authentication.SignInGaiaResponse.Header
	(*SignInGaiaResponse_DeviceData)(nil),               // 34: authentication.SignInGaiaResponse.DeviceData
	(*SignInGaiaResponse_DeviceData_DeviceWrapper)(nil), // 35: authentication.SignInGaiaResponse.DeviceData.DeviceWrapper
	(*RPCGaiaData_UnknownContainer)(nil),                // 36: authentication.RPCGaiaData.UnknownContainer
	(*RPCGaiaData_UnknownContainer_Item2)(nil),          // 37: authentication.RPCGaiaData.UnknownContainer.Item2
	(*RPCGaiaData_UnknownContainer_Item4)(nil),          // 38: authentication.RPCGaiaData.UnknownContainer.Item4
	(*RPCGaiaData_UnknownContainer_Item2_Item1)(nil),    // 39: authentication.RPCGaiaData.UnknownContainer.Item2.Item1
	(*RPCGaiaData_UnknownContainer_Item4_Item8)(nil),    // 40: authentication.RPCGaiaData.UnknownContainer.Item4.Item8
	(*RegisterRefreshRequest_NestedEmptyArr)(nil),       // 41: authentication.RegisterRefreshRequest.NestedEmptyArr
	(*ErrorResponse_ErrorClass)(nil),                    // 42: authentication.ErrorResponse.ErrorClass
	(*EmptyArr)(nil),                                    // 43: util.EmptyArr
}
var file_authentication_proto_depIdxs = []int32{
	0,  // 0: authentication.BrowserDetails.browserType:type_name -> authentication.BrowserType
	1,  // 1: authentication.BrowserDetails.deviceType:type_name -> authentication.DeviceType
	12, // 2: authentication.SignInGaiaRequest.authMessage:type_name -> authentication.AuthMessage
	30, // 3: authentication.SignInGaiaRequest.inner:type_name -> authentication.SignInGaiaRequest.Inner
	33, // 4: authentication.SignInGaiaResponse.header:type_name -> authentication.SignInGaiaResponse.Header
	34, // 5: authentication.SignInGaiaResponse.deviceData:type_name -> authentication.SignInGaiaResponse.DeviceData
	27, // 6: authentication.SignInGaiaResponse.tokenData:type_name -> authentication.TokenData
	2,  // 7: authentication.GaiaPairingRequestContainer.browserDetails:type_name -> authentication.BrowserDetails
	36, // 8: authentication.RPCGaiaData.maybeServerData:type_name -> authentication.RPCGaiaData.UnknownContainer
	12, // 9: authentication.AuthenticationContainer.authMessage:type_name -> authentication.AuthMessage
	2,  // 10: authentication.AuthenticationContainer.browserDetails:type_name -> authentication.BrowserDetails
	24, // 11: authentication.AuthenticationContainer.keyData:type_name -> authentication.KeyData
	23, // 12: authentication.AuthenticationContainer.deviceData:type_name -> authentication.CurrentDeviceData
	4,  // 13: authentication.AuthMessage.configVersion:type_name -> authentication.ConfigVersion
	12, // 14: authentication.RevokeRelayPairingRequest.authMessage:type_name -> authentication.AuthMessage
	3,  // 15: authentication.RevokeRelayPairingRequest.browser:type_name -> authentication.Device
	12, // 16: authentication.RegisterRefreshRequest.messageAuth:type_name -> authentication.AuthMessage
	3,  // 17: authentication.RegisterRefreshRequest.currBrowserDevice:type_name -> authentication.Device
	41, // 18: authentication.RegisterRefreshRequest.emptyRefreshArr:type_name -> authentication.RegisterRefreshRequest.NestedEmptyArr
	27, // 19: authentication.RegisterRefreshResponse.tokenData:type_name -> authentication.TokenData
	18, // 20: authentication.RegisterPhoneRelayResponse.coordinates:type_name -> authentication.CoordinateMessage
	3,  // 21: authentication.RegisterPhoneRelayResponse.browser:type_name -> authentication.Device
	27, // 22: authentication.RegisterPhoneRelayResponse.authKeyData:type_name -> authentication.TokenData
	18, // 23: authentication.RefreshPhoneRelayResponse.coordinates:type_name -> authentication.CoordinateMessage
	18, // 24: authentication.WebEncryptionKeyResponse.coordinates:type_name -> authentication.CoordinateMessage
	42, // 25: authentication.ErrorResponse.class:type_name -> authentication.ErrorResponse.ErrorClass
	3,  // 26: authentication.CurrentDeviceData.browser:type_name -> authentication.Device
	3,  // 27: authentication.KeyData.mobile:type_name -> authentication.Device
	22, // 28: authentication.KeyData.ecdsaKeys:type_name -> authentication.ECDSAKeys
	25, // 29: authentication.KeyData.webAuthKeyData:type_name -> authentication.WebAuthKey
	3,  // 30: authentication.KeyData.browser:type_name -> authentication.Device
	3,  // 31: authentication.PairedData.mobile:type_name -> authentication.Device
	27, // 32: authentication.PairedData.tokenData:type_name -> authentication.TokenData
	3,  // 33: authentication.PairedData.browser:type_name -> authentication.Device
	3,  // 34: authentication.RevokePairData.revokedDevice:type_name -> authentication.Device
	31, // 35: authentication.SignInGaiaRequest.Inner.deviceID:type_name -> authentication.SignInGaiaRequest.Inner.DeviceID
	32, // 36: authentication.SignInGaiaRequest.Inner.someData:type_name -> authentication.SignInGaiaRequest.Inner.Data
	35, // 37: authentication.SignInGaiaResponse.DeviceData.deviceWrapper:type_name -> authentication.SignInGaiaResponse.DeviceData.DeviceWrapper
	39, // 38: authentication.SignInGaiaResponse.DeviceData.unknownItems2:type_name -> authentication.RPCGaiaData.UnknownContainer.Item2.Item1
	38, // 39: authentication.SignInGaiaResponse.DeviceData.unknownItems3:type_name -> authentication.RPCGaiaData.UnknownContainer.Item4
	3,  // 40: authentication.SignInGaiaResponse.DeviceData.DeviceWrapper.device:type_name -> authentication.Device
	37, // 41: authentication.RPCGaiaData.UnknownContainer.item2:type_name -> authentication.RPCGaiaData.UnknownContainer.Item2
	38, // 42: authentication.RPCGaiaData.UnknownContainer.item4:type_name -> authentication.RPCGaiaData.UnknownContainer.Item4
	39, // 43: authentication.RPCGaiaData.UnknownContainer.Item2.item1:type_name -> authentication.RPCGaiaData.UnknownContainer.Item2.Item1
	40, // 44: authentication.RPCGaiaData.UnknownContainer.Item4.item8:type_name -> authentication.RPCGaiaData.UnknownContainer.Item4.Item8
	43, // 45: authentication.RegisterRefreshRequest.NestedEmptyArr.emptyArr:type_name -> util.EmptyArr
	46, // [46:46] is the sub-list for method output_type
	46, // [46:46] is the sub-list for method input_type
	46, // [46:46] is the sub-list for extension type_name
	46, // [46:46] is the sub-list for extension extendee
	0,  // [0:46] is the sub-list for field type_name
}

func init() { file_authentication_proto_init() }
func file_authentication_proto_init() {
	if File_authentication_proto != nil {
		return
	}
	file_util_proto_init()
	file_authentication_proto_msgTypes[9].OneofWrappers = []any{
		(*AuthenticationContainer_KeyData)(nil),
		(*AuthenticationContainer_DeviceData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authentication_proto_rawDesc), len(file_authentication_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   41,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_authentication_proto_goTypes,
		DependencyIndexes: file_authentication_proto_depIdxs,
		EnumInfos:         file_authentication_proto_enumTypes,
		MessageInfos:      file_authentication_proto_msgTypes,
	}.Build()
	File_authentication_proto = out.File
	file_authentication_proto_goTypes = nil
	file_authentication_proto_depIdxs = nil
}
