// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: config.proto

package gmproto

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"

	_ "embed"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientVersion string             `protobuf:"bytes,1,opt,name=clientVersion,proto3" json:"clientVersion,omitempty"`
	ServerVersion string             `protobuf:"bytes,2,opt,name=serverVersion,proto3" json:"serverVersion,omitempty"`
	IntFlags      []*Config_Flag     `protobuf:"bytes,3,rep,name=intFlags,proto3" json:"intFlags,omitempty"`
	MoreFlags     *Config_MoreFlags  `protobuf:"bytes,4,opt,name=moreFlags,proto3" json:"moreFlags,omitempty"`
	DeviceInfo    *Config_DeviceInfo `protobuf:"bytes,5,opt,name=deviceInfo,proto3" json:"deviceInfo,omitempty"`
	// item 6 seems like a list of device infos without device ID?
	CountryCode   string   `protobuf:"bytes,7,opt,name=countryCode,proto3" json:"countryCode,omitempty"`
	UnknownInts   []uint32 `protobuf:"varint,8,rep,packed,name=unknownInts,proto3" json:"unknownInts,omitempty"`
	GeneratedAtMS int64    `protobuf:"varint,9,opt,name=generatedAtMS,proto3" json:"generatedAtMS,omitempty"`
}

func (x *Config) Reset() {
	*x = Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *Config) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *Config) GetIntFlags() []*Config_Flag {
	if x != nil {
		return x.IntFlags
	}
	return nil
}

func (x *Config) GetMoreFlags() *Config_MoreFlags {
	if x != nil {
		return x.MoreFlags
	}
	return nil
}

func (x *Config) GetDeviceInfo() *Config_DeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

func (x *Config) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *Config) GetUnknownInts() []uint32 {
	if x != nil {
		return x.UnknownInts
	}
	return nil
}

func (x *Config) GetGeneratedAtMS() int64 {
	if x != nil {
		return x.GeneratedAtMS
	}
	return 0
}

type Config_Flag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key           string  `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         int32   `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	UnknownField4 *string `protobuf:"bytes,4,opt,name=unknownField4,proto3,oneof" json:"unknownField4,omitempty"`
	UnknownField5 *string `protobuf:"bytes,5,opt,name=unknownField5,proto3,oneof" json:"unknownField5,omitempty"`
}

func (x *Config_Flag) Reset() {
	*x = Config_Flag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_Flag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_Flag) ProtoMessage() {}

func (x *Config_Flag) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_Flag.ProtoReflect.Descriptor instead.
func (*Config_Flag) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Config_Flag) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Config_Flag) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Config_Flag) GetUnknownField4() string {
	if x != nil && x.UnknownField4 != nil {
		return *x.UnknownField4
	}
	return ""
}

func (x *Config_Flag) GetUnknownField5() string {
	if x != nil && x.UnknownField5 != nil {
		return *x.UnknownField5
	}
	return ""
}

type Config_WrappedFlag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string                    `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value *Config_WrappedFlag_Value `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Config_WrappedFlag) Reset() {
	*x = Config_WrappedFlag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_WrappedFlag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_WrappedFlag) ProtoMessage() {}

func (x *Config_WrappedFlag) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_WrappedFlag.ProtoReflect.Descriptor instead.
func (*Config_WrappedFlag) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Config_WrappedFlag) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Config_WrappedFlag) GetValue() *Config_WrappedFlag_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type Config_MoreFlags struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WrappedFlags []*Config_WrappedFlag `protobuf:"bytes,1,rep,name=wrappedFlags,proto3" json:"wrappedFlags,omitempty"`
}

func (x *Config_MoreFlags) Reset() {
	*x = Config_MoreFlags{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_MoreFlags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_MoreFlags) ProtoMessage() {}

func (x *Config_MoreFlags) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_MoreFlags.ProtoReflect.Descriptor instead.
func (*Config_MoreFlags) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Config_MoreFlags) GetWrappedFlags() []*Config_WrappedFlag {
	if x != nil {
		return x.WrappedFlags
	}
	return nil
}

type Config_DeviceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Zero     string `protobuf:"bytes,3,opt,name=zero,proto3" json:"zero,omitempty"`
	DeviceID string `protobuf:"bytes,4,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
}

func (x *Config_DeviceInfo) Reset() {
	*x = Config_DeviceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_DeviceInfo) ProtoMessage() {}

func (x *Config_DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_DeviceInfo.ProtoReflect.Descriptor instead.
func (*Config_DeviceInfo) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0, 3}
}

func (x *Config_DeviceInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Config_DeviceInfo) GetZero() string {
	if x != nil {
		return x.Zero
	}
	return ""
}

func (x *Config_DeviceInfo) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

type Config_WrappedFlag_Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//
	//	*Config_WrappedFlag_Value_IntVal
	//	*Config_WrappedFlag_Value_StrVal
	Value isConfig_WrappedFlag_Value_Value `protobuf_oneof:"value"`
}

func (x *Config_WrappedFlag_Value) Reset() {
	*x = Config_WrappedFlag_Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_config_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_WrappedFlag_Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_WrappedFlag_Value) ProtoMessage() {}

func (x *Config_WrappedFlag_Value) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_WrappedFlag_Value.ProtoReflect.Descriptor instead.
func (*Config_WrappedFlag_Value) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (m *Config_WrappedFlag_Value) GetValue() isConfig_WrappedFlag_Value_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *Config_WrappedFlag_Value) GetIntVal() int32 {
	if x, ok := x.GetValue().(*Config_WrappedFlag_Value_IntVal); ok {
		return x.IntVal
	}
	return 0
}

func (x *Config_WrappedFlag_Value) GetStrVal() string {
	if x, ok := x.GetValue().(*Config_WrappedFlag_Value_StrVal); ok {
		return x.StrVal
	}
	return ""
}

type isConfig_WrappedFlag_Value_Value interface {
	isConfig_WrappedFlag_Value_Value()
}

type Config_WrappedFlag_Value_IntVal struct {
	IntVal int32 `protobuf:"varint,2,opt,name=intVal,proto3,oneof"`
}

type Config_WrappedFlag_Value_StrVal struct {
	StrVal string `protobuf:"bytes,3,opt,name=strVal,proto3,oneof"`
}

func (*Config_WrappedFlag_Value_IntVal) isConfig_WrappedFlag_Value_Value() {}

func (*Config_WrappedFlag_Value_StrVal) isConfig_WrappedFlag_Value_Value() {}

var File_config_proto protoreflect.FileDescriptor

//go:embed config.pb.raw
var file_config_proto_rawDesc []byte

var (
	file_config_proto_rawDescOnce sync.Once
	file_config_proto_rawDescData = file_config_proto_rawDesc
)

func file_config_proto_rawDescGZIP() []byte {
	file_config_proto_rawDescOnce.Do(func() {
		file_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_config_proto_rawDescData)
	})
	return file_config_proto_rawDescData
}

var file_config_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_config_proto_goTypes = []interface{}{
	(*Config)(nil),                   // 0: config.Config
	(*Config_Flag)(nil),              // 1: config.Config.Flag
	(*Config_WrappedFlag)(nil),       // 2: config.Config.WrappedFlag
	(*Config_MoreFlags)(nil),         // 3: config.Config.MoreFlags
	(*Config_DeviceInfo)(nil),        // 4: config.Config.DeviceInfo
	(*Config_WrappedFlag_Value)(nil), // 5: config.Config.WrappedFlag.Value
}
var file_config_proto_depIdxs = []int32{
	1, // 0: config.Config.intFlags:type_name -> config.Config.Flag
	3, // 1: config.Config.moreFlags:type_name -> config.Config.MoreFlags
	4, // 2: config.Config.deviceInfo:type_name -> config.Config.DeviceInfo
	5, // 3: config.Config.WrappedFlag.value:type_name -> config.Config.WrappedFlag.Value
	2, // 4: config.Config.MoreFlags.wrappedFlags:type_name -> config.Config.WrappedFlag
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_config_proto_init() }
func file_config_proto_init() {
	if File_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_Flag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_WrappedFlag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_MoreFlags); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_DeviceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_config_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_WrappedFlag_Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_config_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_config_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*Config_WrappedFlag_Value_IntVal)(nil),
		(*Config_WrappedFlag_Value_StrVal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_proto_goTypes,
		DependencyIndexes: file_config_proto_depIdxs,
		MessageInfos:      file_config_proto_msgTypes,
	}.Build()
	File_config_proto = out.File
	file_config_proto_rawDesc = nil
	file_config_proto_goTypes = nil
	file_config_proto_depIdxs = nil
}
