// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: events.proto

package gmproto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AlertType int32

const (
	AlertType_ALERT_TYPE_UNKNOWN                     AlertType = 0
	AlertType_BROWSER_INACTIVE                       AlertType = 1  // Emitted whenever browser connection becomes inactive
	AlertType_BROWSER_ACTIVE                         AlertType = 2  // Emitted whenever a new browser session is created
	AlertType_MOBILE_DATA_CONNECTION                 AlertType = 3  // Emitted when the paired device connects to data
	AlertType_MOBILE_WIFI_CONNECTION                 AlertType = 4  // Emitted when the paired device connects to wifi
	AlertType_MOBILE_BATTERY_LOW                     AlertType = 5  // Emitted if the paired device reaches low battery
	AlertType_MOBILE_BATTERY_RESTORED                AlertType = 6  // Emitted if the paired device has restored battery enough to not be considered low
	AlertType_BROWSER_INACTIVE_FROM_TIMEOUT          AlertType = 7  // Emitted whenever browser connection becomes inactive due to timeout
	AlertType_BROWSER_INACTIVE_FROM_INACTIVITY       AlertType = 8  // Emitted whenever browser connection becomes inactive due to inactivity
	AlertType_RCS_CONNECTION                         AlertType = 9  // Emitted whenever RCS connection has been established successfully
	AlertType_OBSERVER_REGISTERED                    AlertType = 10 // Unknown
	AlertType_MOBILE_DATABASE_SYNCING                AlertType = 11 // Emitted whenever the paired device is attempting to sync db
	AlertType_MOBILE_DATABASE_SYNC_COMPLETE          AlertType = 12 // Emitted whenever the paired device has completed the db sync
	AlertType_MOBILE_DATABASE_SYNC_STARTED           AlertType = 13 // Emitted whenever the paired device has begun syncing the db
	AlertType_MOBILE_DATABASE_PARTIAL_SYNC_COMPLETED AlertType = 14 // Emitted whenever the paired device has successfully synced a chunk of the db
	AlertType_MOBILE_DATABASE_PARTIAL_SYNC_STARTED   AlertType = 15 // Emitted whenever the paired device has begun syncing a chunk of the db
	AlertType_CONTACTS_REFRESH_STARTED               AlertType = 16 // Emitted whenever the paired device has begun refreshing contacts
	AlertType_CONTACTS_REFRESH_COMPLETED             AlertType = 17 // Emitted whenever the paired device has successfully refreshed contacts
	AlertType_DISCONNECTED_FROM_SATELLITE            AlertType = 18
	AlertType_BR_MESSAGE_RESTORING                   AlertType = 19
	AlertType_BR_MESSAGE_RESTORE_COMPLETED           AlertType = 20
	AlertType_BR_MESSAGE_RESTORE_STARTED             AlertType = 21
	AlertType_PUSH_THROTTLING                        AlertType = 22
	AlertType_PUSH_THROTTLE_STARTED                  AlertType = 23
	AlertType_PUSH_THROTTLE_ENDED                    AlertType = 24
	AlertType_PUSH_THROTTLE_STARTED_IN_DARK_LAUNCH   AlertType = 25
	AlertType_PUSH_THROTTLE_ENDED_IN_DARK_LAUNCH     AlertType = 26
	AlertType_PUSH_THROTTLING_IN_DARK_LAUNCH         AlertType = 27
)

// Enum value maps for AlertType.
var (
	AlertType_name = map[int32]string{
		0:  "ALERT_TYPE_UNKNOWN",
		1:  "BROWSER_INACTIVE",
		2:  "BROWSER_ACTIVE",
		3:  "MOBILE_DATA_CONNECTION",
		4:  "MOBILE_WIFI_CONNECTION",
		5:  "MOBILE_BATTERY_LOW",
		6:  "MOBILE_BATTERY_RESTORED",
		7:  "BROWSER_INACTIVE_FROM_TIMEOUT",
		8:  "BROWSER_INACTIVE_FROM_INACTIVITY",
		9:  "RCS_CONNECTION",
		10: "OBSERVER_REGISTERED",
		11: "MOBILE_DATABASE_SYNCING",
		12: "MOBILE_DATABASE_SYNC_COMPLETE",
		13: "MOBILE_DATABASE_SYNC_STARTED",
		14: "MOBILE_DATABASE_PARTIAL_SYNC_COMPLETED",
		15: "MOBILE_DATABASE_PARTIAL_SYNC_STARTED",
		16: "CONTACTS_REFRESH_STARTED",
		17: "CONTACTS_REFRESH_COMPLETED",
		18: "DISCONNECTED_FROM_SATELLITE",
		19: "BR_MESSAGE_RESTORING",
		20: "BR_MESSAGE_RESTORE_COMPLETED",
		21: "BR_MESSAGE_RESTORE_STARTED",
		22: "PUSH_THROTTLING",
		23: "PUSH_THROTTLE_STARTED",
		24: "PUSH_THROTTLE_ENDED",
		25: "PUSH_THROTTLE_STARTED_IN_DARK_LAUNCH",
		26: "PUSH_THROTTLE_ENDED_IN_DARK_LAUNCH",
		27: "PUSH_THROTTLING_IN_DARK_LAUNCH",
	}
	AlertType_value = map[string]int32{
		"ALERT_TYPE_UNKNOWN":                     0,
		"BROWSER_INACTIVE":                       1,
		"BROWSER_ACTIVE":                         2,
		"MOBILE_DATA_CONNECTION":                 3,
		"MOBILE_WIFI_CONNECTION":                 4,
		"MOBILE_BATTERY_LOW":                     5,
		"MOBILE_BATTERY_RESTORED":                6,
		"BROWSER_INACTIVE_FROM_TIMEOUT":          7,
		"BROWSER_INACTIVE_FROM_INACTIVITY":       8,
		"RCS_CONNECTION":                         9,
		"OBSERVER_REGISTERED":                    10,
		"MOBILE_DATABASE_SYNCING":                11,
		"MOBILE_DATABASE_SYNC_COMPLETE":          12,
		"MOBILE_DATABASE_SYNC_STARTED":           13,
		"MOBILE_DATABASE_PARTIAL_SYNC_COMPLETED": 14,
		"MOBILE_DATABASE_PARTIAL_SYNC_STARTED":   15,
		"CONTACTS_REFRESH_STARTED":               16,
		"CONTACTS_REFRESH_COMPLETED":             17,
		"DISCONNECTED_FROM_SATELLITE":            18,
		"BR_MESSAGE_RESTORING":                   19,
		"BR_MESSAGE_RESTORE_COMPLETED":           20,
		"BR_MESSAGE_RESTORE_STARTED":             21,
		"PUSH_THROTTLING":                        22,
		"PUSH_THROTTLE_STARTED":                  23,
		"PUSH_THROTTLE_ENDED":                    24,
		"PUSH_THROTTLE_STARTED_IN_DARK_LAUNCH":   25,
		"PUSH_THROTTLE_ENDED_IN_DARK_LAUNCH":     26,
		"PUSH_THROTTLING_IN_DARK_LAUNCH":         27,
	}
)

func (x AlertType) Enum() *AlertType {
	p := new(AlertType)
	*p = x
	return p
}

func (x AlertType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertType) Descriptor() protoreflect.EnumDescriptor {
	return file_events_proto_enumTypes[0].Descriptor()
}

func (AlertType) Type() protoreflect.EnumType {
	return &file_events_proto_enumTypes[0]
}

func (x AlertType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertType.Descriptor instead.
func (AlertType) EnumDescriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0}
}

type TypingTypes int32

const (
	TypingTypes_STOPPED_TYPING TypingTypes = 0
	TypingTypes_STARTED_TYPING TypingTypes = 1
)

// Enum value maps for TypingTypes.
var (
	TypingTypes_name = map[int32]string{
		0: "STOPPED_TYPING",
		1: "STARTED_TYPING",
	}
	TypingTypes_value = map[string]int32{
		"STOPPED_TYPING": 0,
		"STARTED_TYPING": 1,
	}
)

func (x TypingTypes) Enum() *TypingTypes {
	p := new(TypingTypes)
	*p = x
	return p
}

func (x TypingTypes) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TypingTypes) Descriptor() protoreflect.EnumDescriptor {
	return file_events_proto_enumTypes[1].Descriptor()
}

func (TypingTypes) Type() protoreflect.EnumType {
	return &file_events_proto_enumTypes[1]
}

func (x TypingTypes) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TypingTypes.Descriptor instead.
func (TypingTypes) EnumDescriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{1}
}

type UpdateEvents struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*UpdateEvents_ConversationEvent
	//	*UpdateEvents_MessageEvent
	//	*UpdateEvents_TypingEvent
	//	*UpdateEvents_SettingsEvent
	//	*UpdateEvents_UserAlertEvent
	//	*UpdateEvents_BrowserPresenceCheckEvent
	//	*UpdateEvents_AccountChange
	Event         isUpdateEvents_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEvents) Reset() {
	*x = UpdateEvents{}
	mi := &file_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEvents) ProtoMessage() {}

func (x *UpdateEvents) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEvents.ProtoReflect.Descriptor instead.
func (*UpdateEvents) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateEvents) GetEvent() isUpdateEvents_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *UpdateEvents) GetConversationEvent() *ConversationEvent {
	if x != nil {
		if x, ok := x.Event.(*UpdateEvents_ConversationEvent); ok {
			return x.ConversationEvent
		}
	}
	return nil
}

func (x *UpdateEvents) GetMessageEvent() *MessageEvent {
	if x != nil {
		if x, ok := x.Event.(*UpdateEvents_MessageEvent); ok {
			return x.MessageEvent
		}
	}
	return nil
}

func (x *UpdateEvents) GetTypingEvent() *TypingEvent {
	if x != nil {
		if x, ok := x.Event.(*UpdateEvents_TypingEvent); ok {
			return x.TypingEvent
		}
	}
	return nil
}

func (x *UpdateEvents) GetSettingsEvent() *Settings {
	if x != nil {
		if x, ok := x.Event.(*UpdateEvents_SettingsEvent); ok {
			return x.SettingsEvent
		}
	}
	return nil
}

func (x *UpdateEvents) GetUserAlertEvent() *UserAlertEvent {
	if x != nil {
		if x, ok := x.Event.(*UpdateEvents_UserAlertEvent); ok {
			return x.UserAlertEvent
		}
	}
	return nil
}

func (x *UpdateEvents) GetBrowserPresenceCheckEvent() *BrowserPresenceCheckEvent {
	if x != nil {
		if x, ok := x.Event.(*UpdateEvents_BrowserPresenceCheckEvent); ok {
			return x.BrowserPresenceCheckEvent
		}
	}
	return nil
}

func (x *UpdateEvents) GetAccountChange() *AccountChangeOrSomethingEvent {
	if x != nil {
		if x, ok := x.Event.(*UpdateEvents_AccountChange); ok {
			return x.AccountChange
		}
	}
	return nil
}

type isUpdateEvents_Event interface {
	isUpdateEvents_Event()
}

type UpdateEvents_ConversationEvent struct {
	ConversationEvent *ConversationEvent `protobuf:"bytes,2,opt,name=conversationEvent,proto3,oneof"`
}

type UpdateEvents_MessageEvent struct {
	MessageEvent *MessageEvent `protobuf:"bytes,3,opt,name=messageEvent,proto3,oneof"`
}

type UpdateEvents_TypingEvent struct {
	TypingEvent *TypingEvent `protobuf:"bytes,4,opt,name=typingEvent,proto3,oneof"`
}

type UpdateEvents_SettingsEvent struct {
	SettingsEvent *Settings `protobuf:"bytes,5,opt,name=settingsEvent,proto3,oneof"`
}

type UpdateEvents_UserAlertEvent struct {
	UserAlertEvent *UserAlertEvent `protobuf:"bytes,6,opt,name=userAlertEvent,proto3,oneof"`
}

type UpdateEvents_BrowserPresenceCheckEvent struct {
	BrowserPresenceCheckEvent *BrowserPresenceCheckEvent `protobuf:"bytes,7,opt,name=browserPresenceCheckEvent,proto3,oneof"`
}

type UpdateEvents_AccountChange struct {
	// ParticipantsEvent participantsEvent = 8;
	// ConversationTypeEvent conversationTypeEvent = 9;
	// FavoriteStickersEvent favoriteStickersEvent = 10;
	// RecentStickerEvent recentStickerEvent = 11;
	// CloudStoreInfoEvent cloudStoreInfoEvent = 12;
	// BlobForAttachmentProgressUpdate blobForAttachmentProgressUpdate = 13;
	AccountChange *AccountChangeOrSomethingEvent `protobuf:"bytes,15,opt,name=accountChange,proto3,oneof"`
}

func (*UpdateEvents_ConversationEvent) isUpdateEvents_Event() {}

func (*UpdateEvents_MessageEvent) isUpdateEvents_Event() {}

func (*UpdateEvents_TypingEvent) isUpdateEvents_Event() {}

func (*UpdateEvents_SettingsEvent) isUpdateEvents_Event() {}

func (*UpdateEvents_UserAlertEvent) isUpdateEvents_Event() {}

func (*UpdateEvents_BrowserPresenceCheckEvent) isUpdateEvents_Event() {}

func (*UpdateEvents_AccountChange) isUpdateEvents_Event() {}

type EncryptedData2Container struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	AccountChange *AccountChangeOrSomethingEvent `protobuf:"bytes,2,opt,name=accountChange,proto3" json:"accountChange,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptedData2Container) Reset() {
	*x = EncryptedData2Container{}
	mi := &file_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedData2Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedData2Container) ProtoMessage() {}

func (x *EncryptedData2Container) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedData2Container.ProtoReflect.Descriptor instead.
func (*EncryptedData2Container) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{1}
}

func (x *EncryptedData2Container) GetAccountChange() *AccountChangeOrSomethingEvent {
	if x != nil {
		return x.AccountChange
	}
	return nil
}

type AccountChangeOrSomethingEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountChangeOrSomethingEvent) Reset() {
	*x = AccountChangeOrSomethingEvent{}
	mi := &file_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountChangeOrSomethingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountChangeOrSomethingEvent) ProtoMessage() {}

func (x *AccountChangeOrSomethingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountChangeOrSomethingEvent.ProtoReflect.Descriptor instead.
func (*AccountChangeOrSomethingEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{2}
}

func (x *AccountChangeOrSomethingEvent) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *AccountChangeOrSomethingEvent) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type ConversationEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Conversation        `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationEvent) Reset() {
	*x = ConversationEvent{}
	mi := &file_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationEvent) ProtoMessage() {}

func (x *ConversationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationEvent.ProtoReflect.Descriptor instead.
func (*ConversationEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{3}
}

func (x *ConversationEvent) GetData() []*Conversation {
	if x != nil {
		return x.Data
	}
	return nil
}

type TypingEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *TypingData            `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypingEvent) Reset() {
	*x = TypingEvent{}
	mi := &file_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypingEvent) ProtoMessage() {}

func (x *TypingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypingEvent.ProtoReflect.Descriptor instead.
func (*TypingEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{4}
}

func (x *TypingEvent) GetData() *TypingData {
	if x != nil {
		return x.Data
	}
	return nil
}

type MessageEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Message             `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageEvent) Reset() {
	*x = MessageEvent{}
	mi := &file_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEvent) ProtoMessage() {}

func (x *MessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEvent.ProtoReflect.Descriptor instead.
func (*MessageEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{5}
}

func (x *MessageEvent) GetData() []*Message {
	if x != nil {
		return x.Data
	}
	return nil
}

type UserAlertEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlertType     AlertType              `protobuf:"varint,2,opt,name=alertType,proto3,enum=events.AlertType" json:"alertType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAlertEvent) Reset() {
	*x = UserAlertEvent{}
	mi := &file_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAlertEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAlertEvent) ProtoMessage() {}

func (x *UserAlertEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAlertEvent.ProtoReflect.Descriptor instead.
func (*UserAlertEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{6}
}

func (x *UserAlertEvent) GetAlertType() AlertType {
	if x != nil {
		return x.AlertType
	}
	return AlertType_ALERT_TYPE_UNKNOWN
}

type BrowserPresenceCheckEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrowserPresenceCheckEvent) Reset() {
	*x = BrowserPresenceCheckEvent{}
	mi := &file_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrowserPresenceCheckEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowserPresenceCheckEvent) ProtoMessage() {}

func (x *BrowserPresenceCheckEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowserPresenceCheckEvent.ProtoReflect.Descriptor instead.
func (*BrowserPresenceCheckEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{7}
}

type TypingData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationID string                 `protobuf:"bytes,1,opt,name=conversationID,proto3" json:"conversationID,omitempty"`
	User           *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Type           TypingTypes            `protobuf:"varint,3,opt,name=type,proto3,enum=events.TypingTypes" json:"type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TypingData) Reset() {
	*x = TypingData{}
	mi := &file_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypingData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypingData) ProtoMessage() {}

func (x *TypingData) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypingData.ProtoReflect.Descriptor instead.
func (*TypingData) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{8}
}

func (x *TypingData) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

func (x *TypingData) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *TypingData) GetType() TypingTypes {
	if x != nil {
		return x.Type
	}
	return TypingTypes_STOPPED_TYPING
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field1        int64                  `protobuf:"varint,1,opt,name=field1,proto3" json:"field1,omitempty"`
	Number        string                 `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{9}
}

func (x *User) GetField1() int64 {
	if x != nil {
		return x.Field1
	}
	return 0
}

func (x *User) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

type RPCPairData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*RPCPairData_Paired
	//	*RPCPairData_Revoked
	Event         isRPCPairData_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPCPairData) Reset() {
	*x = RPCPairData{}
	mi := &file_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPCPairData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCPairData) ProtoMessage() {}

func (x *RPCPairData) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCPairData.ProtoReflect.Descriptor instead.
func (*RPCPairData) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{10}
}

func (x *RPCPairData) GetEvent() isRPCPairData_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *RPCPairData) GetPaired() *PairedData {
	if x != nil {
		if x, ok := x.Event.(*RPCPairData_Paired); ok {
			return x.Paired
		}
	}
	return nil
}

func (x *RPCPairData) GetRevoked() *RevokePairData {
	if x != nil {
		if x, ok := x.Event.(*RPCPairData_Revoked); ok {
			return x.Revoked
		}
	}
	return nil
}

type isRPCPairData_Event interface {
	isRPCPairData_Event()
}

type RPCPairData_Paired struct {
	Paired *PairedData `protobuf:"bytes,4,opt,name=paired,proto3,oneof"`
}

type RPCPairData_Revoked struct {
	Revoked *RevokePairData `protobuf:"bytes,5,opt,name=revoked,proto3,oneof"`
}

func (*RPCPairData_Paired) isRPCPairData_Event() {}

func (*RPCPairData_Revoked) isRPCPairData_Event() {}

var File_events_proto protoreflect.FileDescriptor

const file_events_proto_rawDesc = "" +
	"\n" +
	"\fevents.proto\x12\x06events\x1a\x13conversations.proto\x1a\x14authentication.proto\x1a\x0esettings.proto\"\x87\x04\n" +
	"\fUpdateEvents\x12I\n" +
	"\x11conversationEvent\x18\x02 \x01(\v2\x19.events.ConversationEventH\x00R\x11conversationEvent\x12:\n" +
	"\fmessageEvent\x18\x03 \x01(\v2\x14.events.MessageEventH\x00R\fmessageEvent\x127\n" +
	"\vtypingEvent\x18\x04 \x01(\v2\x13.events.TypingEventH\x00R\vtypingEvent\x12:\n" +
	"\rsettingsEvent\x18\x05 \x01(\v2\x12.settings.SettingsH\x00R\rsettingsEvent\x12@\n" +
	"\x0euserAlertEvent\x18\x06 \x01(\v2\x16.events.UserAlertEventH\x00R\x0euserAlertEvent\x12a\n" +
	"\x19browserPresenceCheckEvent\x18\a \x01(\v2!.events.BrowserPresenceCheckEventH\x00R\x19browserPresenceCheckEvent\x12M\n" +
	"\raccountChange\x18\x0f \x01(\v2%.events.AccountChangeOrSomethingEventH\x00R\raccountChangeB\a\n" +
	"\x05event\"f\n" +
	"\x17EncryptedData2Container\x12K\n" +
	"\raccountChange\x18\x02 \x01(\v2%.events.AccountChangeOrSomethingEventR\raccountChange\"S\n" +
	"\x1dAccountChangeOrSomethingEvent\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\"D\n" +
	"\x11ConversationEvent\x12/\n" +
	"\x04data\x18\x02 \x03(\v2\x1b.conversations.ConversationR\x04data\"5\n" +
	"\vTypingEvent\x12&\n" +
	"\x04data\x18\x02 \x01(\v2\x12.events.TypingDataR\x04data\":\n" +
	"\fMessageEvent\x12*\n" +
	"\x04data\x18\x02 \x03(\v2\x16.conversations.MessageR\x04data\"A\n" +
	"\x0eUserAlertEvent\x12/\n" +
	"\talertType\x18\x02 \x01(\x0e2\x11.events.AlertTypeR\talertType\"\x1b\n" +
	"\x19BrowserPresenceCheckEvent\"\x7f\n" +
	"\n" +
	"TypingData\x12&\n" +
	"\x0econversationID\x18\x01 \x01(\tR\x0econversationID\x12 \n" +
	"\x04user\x18\x02 \x01(\v2\f.events.UserR\x04user\x12'\n" +
	"\x04type\x18\x03 \x01(\x0e2\x13.events.TypingTypesR\x04type\"6\n" +
	"\x04User\x12\x16\n" +
	"\x06field1\x18\x01 \x01(\x03R\x06field1\x12\x16\n" +
	"\x06number\x18\x02 \x01(\tR\x06number\"\x88\x01\n" +
	"\vRPCPairData\x124\n" +
	"\x06paired\x18\x04 \x01(\v2\x1a.authentication.PairedDataH\x00R\x06paired\x12:\n" +
	"\arevoked\x18\x05 \x01(\v2\x1e.authentication.RevokePairDataH\x00R\arevokedB\a\n" +
	"\x05event*\xe2\x06\n" +
	"\tAlertType\x12\x16\n" +
	"\x12ALERT_TYPE_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10BROWSER_INACTIVE\x10\x01\x12\x12\n" +
	"\x0eBROWSER_ACTIVE\x10\x02\x12\x1a\n" +
	"\x16MOBILE_DATA_CONNECTION\x10\x03\x12\x1a\n" +
	"\x16MOBILE_WIFI_CONNECTION\x10\x04\x12\x16\n" +
	"\x12MOBILE_BATTERY_LOW\x10\x05\x12\x1b\n" +
	"\x17MOBILE_BATTERY_RESTORED\x10\x06\x12!\n" +
	"\x1dBROWSER_INACTIVE_FROM_TIMEOUT\x10\a\x12$\n" +
	" BROWSER_INACTIVE_FROM_INACTIVITY\x10\b\x12\x12\n" +
	"\x0eRCS_CONNECTION\x10\t\x12\x17\n" +
	"\x13OBSERVER_REGISTERED\x10\n" +
	"\x12\x1b\n" +
	"\x17MOBILE_DATABASE_SYNCING\x10\v\x12!\n" +
	"\x1dMOBILE_DATABASE_SYNC_COMPLETE\x10\f\x12 \n" +
	"\x1cMOBILE_DATABASE_SYNC_STARTED\x10\r\x12*\n" +
	"&MOBILE_DATABASE_PARTIAL_SYNC_COMPLETED\x10\x0e\x12(\n" +
	"$MOBILE_DATABASE_PARTIAL_SYNC_STARTED\x10\x0f\x12\x1c\n" +
	"\x18CONTACTS_REFRESH_STARTED\x10\x10\x12\x1e\n" +
	"\x1aCONTACTS_REFRESH_COMPLETED\x10\x11\x12\x1f\n" +
	"\x1bDISCONNECTED_FROM_SATELLITE\x10\x12\x12\x18\n" +
	"\x14BR_MESSAGE_RESTORING\x10\x13\x12 \n" +
	"\x1cBR_MESSAGE_RESTORE_COMPLETED\x10\x14\x12\x1e\n" +
	"\x1aBR_MESSAGE_RESTORE_STARTED\x10\x15\x12\x13\n" +
	"\x0fPUSH_THROTTLING\x10\x16\x12\x19\n" +
	"\x15PUSH_THROTTLE_STARTED\x10\x17\x12\x17\n" +
	"\x13PUSH_THROTTLE_ENDED\x10\x18\x12(\n" +
	"$PUSH_THROTTLE_STARTED_IN_DARK_LAUNCH\x10\x19\x12&\n" +
	"\"PUSH_THROTTLE_ENDED_IN_DARK_LAUNCH\x10\x1a\x12\"\n" +
	"\x1ePUSH_THROTTLING_IN_DARK_LAUNCH\x10\x1b*5\n" +
	"\vTypingTypes\x12\x12\n" +
	"\x0eSTOPPED_TYPING\x10\x00\x12\x12\n" +
	"\x0eSTARTED_TYPING\x10\x01B\fZ\n" +
	"../gmprotob\x06proto3"

var (
	file_events_proto_rawDescOnce sync.Once
	file_events_proto_rawDescData []byte
)

func file_events_proto_rawDescGZIP() []byte {
	file_events_proto_rawDescOnce.Do(func() {
		file_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)))
	})
	return file_events_proto_rawDescData
}

var file_events_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_events_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_events_proto_goTypes = []any{
	(AlertType)(0),                        // 0: events.AlertType
	(TypingTypes)(0),                      // 1: events.TypingTypes
	(*UpdateEvents)(nil),                  // 2: events.UpdateEvents
	(*EncryptedData2Container)(nil),       // 3: events.EncryptedData2Container
	(*AccountChangeOrSomethingEvent)(nil), // 4: events.AccountChangeOrSomethingEvent
	(*ConversationEvent)(nil),             // 5: events.ConversationEvent
	(*TypingEvent)(nil),                   // 6: events.TypingEvent
	(*MessageEvent)(nil),                  // 7: events.MessageEvent
	(*UserAlertEvent)(nil),                // 8: events.UserAlertEvent
	(*BrowserPresenceCheckEvent)(nil),     // 9: events.BrowserPresenceCheckEvent
	(*TypingData)(nil),                    // 10: events.TypingData
	(*User)(nil),                          // 11: events.User
	(*RPCPairData)(nil),                   // 12: events.RPCPairData
	(*Settings)(nil),                      // 13: settings.Settings
	(*Conversation)(nil),                  // 14: conversations.Conversation
	(*Message)(nil),                       // 15: conversations.Message
	(*PairedData)(nil),                    // 16: authentication.PairedData
	(*RevokePairData)(nil),                // 17: authentication.RevokePairData
}
var file_events_proto_depIdxs = []int32{
	5,  // 0: events.UpdateEvents.conversationEvent:type_name -> events.ConversationEvent
	7,  // 1: events.UpdateEvents.messageEvent:type_name -> events.MessageEvent
	6,  // 2: events.UpdateEvents.typingEvent:type_name -> events.TypingEvent
	13, // 3: events.UpdateEvents.settingsEvent:type_name -> settings.Settings
	8,  // 4: events.UpdateEvents.userAlertEvent:type_name -> events.UserAlertEvent
	9,  // 5: events.UpdateEvents.browserPresenceCheckEvent:type_name -> events.BrowserPresenceCheckEvent
	4,  // 6: events.UpdateEvents.accountChange:type_name -> events.AccountChangeOrSomethingEvent
	4,  // 7: events.EncryptedData2Container.accountChange:type_name -> events.AccountChangeOrSomethingEvent
	14, // 8: events.ConversationEvent.data:type_name -> conversations.Conversation
	10, // 9: events.TypingEvent.data:type_name -> events.TypingData
	15, // 10: events.MessageEvent.data:type_name -> conversations.Message
	0,  // 11: events.UserAlertEvent.alertType:type_name -> events.AlertType
	11, // 12: events.TypingData.user:type_name -> events.User
	1,  // 13: events.TypingData.type:type_name -> events.TypingTypes
	16, // 14: events.RPCPairData.paired:type_name -> authentication.PairedData
	17, // 15: events.RPCPairData.revoked:type_name -> authentication.RevokePairData
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_events_proto_init() }
func file_events_proto_init() {
	if File_events_proto != nil {
		return
	}
	file_conversations_proto_init()
	file_authentication_proto_init()
	file_settings_proto_init()
	file_events_proto_msgTypes[0].OneofWrappers = []any{
		(*UpdateEvents_ConversationEvent)(nil),
		(*UpdateEvents_MessageEvent)(nil),
		(*UpdateEvents_TypingEvent)(nil),
		(*UpdateEvents_SettingsEvent)(nil),
		(*UpdateEvents_UserAlertEvent)(nil),
		(*UpdateEvents_BrowserPresenceCheckEvent)(nil),
		(*UpdateEvents_AccountChange)(nil),
	}
	file_events_proto_msgTypes[10].OneofWrappers = []any{
		(*RPCPairData_Paired)(nil),
		(*RPCPairData_Revoked)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_proto_goTypes,
		DependencyIndexes: file_events_proto_depIdxs,
		EnumInfos:         file_events_proto_enumTypes,
		MessageInfos:      file_events_proto_msgTypes,
	}.Build()
	File_events_proto = out.File
	file_events_proto_goTypes = nil
	file_events_proto_depIdxs = nil
}
